import { randomUUID } from "node:crypto";
import type { ParsedConversation, RoastReport } from "@/domain/report";
import { formatDateRange } from "@/lib/whatsapp";

type Copy = {
  titles: string[];
  title: (chat: string) => string;
  subtitle: string;
  portrait: (name: string, share: number, first: boolean) => string;
  firstLine: string;
  otherLine: string;
  opening: (chat: string, top: string) => string;
  awards: (top: string, quiet: string, second: string) => RoastReport["awards"];
  dictionary: RoastReport["dictionary"];
  dynamics: (top: string) => string[];
  flags: RoastReport["flags"];
  reaction: (position: "first" | "last" | "middle") => string;
  verdict: (chat: string) => string;
};

const en: Copy = {
  titles: ["The Unofficial Project Manager", "Chief Reaction Officer", "The Plot Twist Department", "Director of Strategic Disappearing", "Keeper of the Lore"],
  title: (chat) => `${chat}: A Beautifully Managed Disaster`,
  subtitle: "A forensic reading of the plans, disappearances and deeply unnecessary voice notes.",
  portrait: (name, share, first) => `${name} contributes ${share}% of the chat and has somehow turned that into a full-time personality trait. ${first ? "If this group has a steering wheel, they are holding it." : "They may not run the chat, but the timing of their entrances deserves its own study."}`,
  firstLine: "Not controlling. Just correctly concerned that nobody else made a plan.", otherLine: "Present when the plot needs them, mysteriously offline when logistics appear.",
  opening: (chat, top) => `${chat} is held together by affection, repeated questions nobody answers, and ${top}'s refusal to let a plan die quietly. It works. Nobody knows why, but it works.`,
  awards: (top, quiet, second) => [{ title: "Most likely to make the plan real", winner: top, reason: "Message volume says leadership. The follow-ups say mild exhaustion." }, { title: "Best surprise appearance", winner: quiet, reason: "Low frequency. Maximum narrative impact." }, { title: "The ‘on my way’ lifetime achievement award", winner: second, reason: "The committee checked the timestamps. The committee has concerns." }],
  dictionary: [{ term: "We should", meaning: "This will not happen without a second, more serious message." }, { term: "Hahaha", meaning: "Acknowledged. No further action will be taken." }, { term: "On my way", meaning: "A broad statement of future intent." }],
  dynamics: (top) => [`${top} creates momentum; everyone else creates texture.`, "Plans require at least three emotional phases before becoming calendar events.", "Silence is usually someone preparing a reaction emoji."],
  flags: { green: ["You keep returning to each other", "The group has a shared language outsiders would not survive"], yellow: ["Questions regularly become archaeological artefacts", "Planning depends on one suspiciously competent person"], red: ["‘On my way’ appears to be legally non-binding"] },
  reaction: (position) => position === "first" ? "Will send three corrections, then quietly save the report." : position === "last" ? "Will read every word and respond with one emoji." : "Will deny it before quoting their favourite section.",
  verdict: (chat) => `${chat} is a tiny institution with no constitution, inconsistent office hours, and surprisingly excellent retention. The chaos is not a bug. It is the group culture.`,
};

const copies: Record<string, Copy> = {
  en,
  fr: { ...en, titles: ["Chef de projet non officiel", "Direction générale des réactions", "Service des rebondissements", "Responsable des disparitions stratégiques", "Gardien des dossiers"], title: (chat) => `${chat} : un désastre magnifiquement organisé`, subtitle: "Une lecture minutieuse des plans, disparitions et vocaux franchement dispensables.", portrait: (name, share, first) => `${name} signe ${share} % du chat et en a fait un trait de personnalité à temps plein. ${first ? "Si ce groupe a un volant, cette personne le tient." : "Cette personne ne dirige peut-être pas le chat, mais le timing de ses apparitions mérite une étude."}`, firstLine: "Pas autoritaire. Juste légitimement inquiet que personne d’autre n’ait fait de plan.", otherLine: "Présent quand l’intrigue l’exige, mystérieusement hors ligne dès que la logistique apparaît.", opening: (chat, top) => `${chat} tient grâce à l’affection, aux questions répétées auxquelles personne ne répond et au refus de ${top} de laisser un plan mourir en silence. Cela fonctionne. Personne ne sait pourquoi, mais cela fonctionne.`, awards: (top, quiet, second) => [{ title: "Plan le plus susceptible d’exister", winner: top, reason: "Le volume de messages dit leadership. Les relances disent légère fatigue." }, { title: "Meilleure apparition surprise", winner: quiet, reason: "Faible fréquence. Impact narratif maximal." }, { title: "Prix d’honneur du « j’arrive »", winner: second, reason: "Le jury a vérifié les horaires. Le jury s’inquiète." }], dictionary: [{ term: "Il faudrait", meaning: "Rien ne se passera sans un deuxième message plus sérieux." }, { term: "Hahaha", meaning: "Message reçu. Aucune autre action ne sera entreprise." }, { term: "J’arrive", meaning: "Déclaration très large d’intention future." }], dynamics: (top) => [`${top} crée l’élan ; les autres créent la texture.`, "Chaque plan traverse au moins trois phases émotionnelles avant d’atteindre un calendrier.", "Le silence signifie souvent que quelqu’un prépare un emoji de réaction."], flags: { green: ["Vous revenez toujours les uns vers les autres", "Le groupe parle une langue commune que les autres ne survivraient pas"], yellow: ["Les questions deviennent régulièrement des pièces archéologiques", "L’organisation dépend d’une personne étrangement compétente"], red: ["« J’arrive » ne semble avoir aucune valeur contractuelle"] }, reaction: (position) => position === "first" ? "Enverra trois corrections, puis sauvegardera discrètement le rapport." : position === "last" ? "Lira tout et répondra avec un seul emoji." : "Niera avant de citer sa section préférée.", verdict: (chat) => `${chat} est une petite institution sans constitution, aux horaires incohérents et à la fidélité étonnante. Le chaos n’est pas un bug. C’est la culture du groupe.` },
  es: { ...en, titles: ["Director de proyecto no oficial", "Responsable de reacciones", "Departamento de giros de guion", "Director de desapariciones estratégicas", "Guardián de la historia"], title: (chat) => `${chat}: un desastre maravillosamente organizado`, subtitle: "Una lectura forense de los planes, desapariciones y audios totalmente innecesarios.", portrait: (name, share, first) => `${name} aporta el ${share}% del chat y lo ha convertido en un rasgo de personalidad a tiempo completo. ${first ? "Si este grupo tiene volante, lo lleva esta persona." : "Quizá no dirija el chat, pero el momento de sus apariciones merece un estudio."}`, firstLine: "No controla. Solo le preocupa, con razón, que nadie más haya hecho un plan.", otherLine: "Presente cuando la trama lo necesita, misteriosamente ausente cuando aparece la logística.", opening: (chat, top) => `${chat} se sostiene con cariño, preguntas repetidas que nadie responde y la negativa de ${top} a dejar morir un plan en silencio. Funciona. Nadie sabe por qué, pero funciona.`, awards: (top, quiet, second) => [{ title: "Plan con más opciones de hacerse realidad", winner: top, reason: "El volumen dice liderazgo. Los recordatorios dicen cansancio leve." }, { title: "Mejor aparición sorpresa", winner: quiet, reason: "Poca frecuencia. Máximo impacto narrativo." }, { title: "Premio honorífico al «ya voy»", winner: second, reason: "El jurado revisó las horas. El jurado tiene dudas." }], dictionary: [{ term: "Deberíamos", meaning: "No pasará nada sin un segundo mensaje más serio." }, { term: "Jajaja", meaning: "Recibido. No se tomará ninguna otra medida." }, { term: "Ya voy", meaning: "Una declaración amplia de intención futura." }], dynamics: (top) => [`${top} crea impulso; el resto aporta textura.`, "Los planes necesitan tres fases emocionales antes de llegar al calendario.", "El silencio suele ser alguien preparando un emoji."], flags: { green: ["Siempre volvéis al grupo", "Tenéis un idioma compartido imposible para los de fuera"], yellow: ["Las preguntas acaban como piezas arqueológicas", "La organización depende de una persona sospechosamente competente"], red: ["«Ya voy» parece no ser vinculante"] }, reaction: (position) => position === "first" ? "Mandará tres correcciones y guardará el informe en silencio." : position === "last" ? "Lo leerá entero y responderá con un emoji." : "Lo negará antes de citar su parte favorita.", verdict: (chat) => `${chat} es una pequeña institución sin constitución, con horarios incoherentes y una retención excelente. El caos no es un error. Es la cultura del grupo.` },
  it: { ...en, titles: ["Project manager non ufficiale", "Responsabile delle reazioni", "Dipartimento dei colpi di scena", "Direttore delle sparizioni strategiche", "Custode della storia"], title: (chat) => `${chat}: un disastro splendidamente organizzato`, subtitle: "Una lettura forense di piani, sparizioni e vocali davvero superflui.", portrait: (name, share, first) => `${name} firma il ${share}% della chat e ne ha fatto un tratto della personalità a tempo pieno. ${first ? "Se questo gruppo ha un volante, lo tiene questa persona." : "Forse non guida la chat, ma il tempismo delle sue entrate merita uno studio."}`, firstLine: "Non controlla. È solo giustamente preoccupato che nessun altro abbia fatto un piano.", otherLine: "Presente quando serve alla trama, misteriosamente offline quando arriva la logistica.", opening: (chat, top) => `${chat} sta insieme grazie all’affetto, alle domande ripetute senza risposta e al rifiuto di ${top} di lasciar morire un piano in silenzio. Funziona. Nessuno sa perché, ma funziona.`, awards: (top, quiet, second) => [{ title: "Piano con più possibilità di esistere", winner: top, reason: "Il volume dice leadership. I solleciti dicono lieve stanchezza." }, { title: "Migliore apparizione a sorpresa", winner: quiet, reason: "Bassa frequenza. Massimo impatto narrativo." }, { title: "Premio alla carriera per «sto arrivando»", winner: second, reason: "La giuria ha controllato gli orari. La giuria è preoccupata." }], dictionary: [{ term: "Dovremmo", meaning: "Non succederà senza un secondo messaggio più serio." }, { term: "Ahaha", meaning: "Ricevuto. Non seguiranno altre azioni." }, { term: "Sto arrivando", meaning: "Ampia dichiarazione di intenzioni future." }], dynamics: (top) => [`${top} crea slancio; gli altri creano atmosfera.`, "Ogni piano attraversa tre fasi emotive prima del calendario.", "Il silenzio spesso è qualcuno che prepara un’emoji."], flags: { green: ["Continuate a tornarvi incontro", "Il gruppo ha una lingua condivisa incomprensibile agli estranei"], yellow: ["Le domande diventano reperti archeologici", "L’organizzazione dipende da una persona sospettosamente competente"], red: ["«Sto arrivando» sembra non avere valore legale"] }, reaction: (position) => position === "first" ? "Manderà tre correzioni e poi salverà il report in silenzio." : position === "last" ? "Leggerà tutto e risponderà con una sola emoji." : "Ngherà tutto prima di citare la parte preferita.", verdict: (chat) => `${chat} è una piccola istituzione senza costituzione, con orari incoerenti e una fedeltà sorprendente. Il caos non è un bug. È la cultura del gruppo.` },
  de: { ...en, titles: ["Inoffizielle Projektleitung", "Leitung Reaktionswesen", "Abteilung Plot-Twist", "Direktion strategisches Verschwinden", "Hüter der Gruppenchronik"], title: (chat) => `${chat}: ein wunderschön organisiertes Desaster`, subtitle: "Eine forensische Auswertung von Plänen, Verschwinden und unnötig langen Sprachnachrichten.", portrait: (name, share, first) => `${name} schreibt ${share} % des Chats und hat daraus einen Vollzeit-Charakterzug gemacht. ${first ? "Wenn diese Gruppe ein Lenkrad hat, hält diese Person es fest." : "Diese Person führt den Chat vielleicht nicht, aber das Timing ihrer Auftritte verdient eine Studie."}`, firstLine: "Nicht kontrollierend. Nur zu Recht besorgt, dass sonst niemand einen Plan gemacht hat.", otherLine: "Da, wenn die Handlung es braucht; rätselhaft offline, sobald Logistik auftaucht.", opening: (chat, top) => `${chat} wird von Zuneigung, wiederholten unbeantworteten Fragen und ${top}s Weigerung zusammengehalten, einen Plan still sterben zu lassen. Es funktioniert. Niemand weiß warum, aber es funktioniert.`, awards: (top, quiet, second) => [{ title: "Plan mit der besten Überlebenschance", winner: top, reason: "Die Nachrichtenmenge sagt Führung. Die Nachfragen sagen leichte Erschöpfung." }, { title: "Bester Überraschungsauftritt", winner: quiet, reason: "Selten. Maximale Wirkung." }, { title: "Lebenswerkpreis für ‚Bin unterwegs‘", winner: second, reason: "Die Jury hat die Zeitstempel geprüft. Die Jury ist besorgt." }], dictionary: [{ term: "Wir sollten", meaning: "Ohne eine zweite, ernstere Nachricht wird nichts passieren." }, { term: "Hahaha", meaning: "Zur Kenntnis genommen. Weitere Schritte folgen nicht." }, { term: "Bin unterwegs", meaning: "Eine großzügige Aussage über zukünftige Absichten." }], dynamics: (top) => [`${top} sorgt für Schwung; alle anderen für Atmosphäre.`, "Pläne brauchen drei emotionale Phasen bis zum Kalender.", "Stille bedeutet meist, dass jemand ein Reaktions-Emoji vorbereitet."], flags: { green: ["Ihr findet immer wieder zueinander", "Die Gruppe hat eine gemeinsame Sprache, die Außenstehende nicht überleben würden"], yellow: ["Fragen werden regelmäßig zu archäologischen Fundstücken", "Die Planung hängt von einer verdächtig kompetenten Person ab"], red: ["‚Bin unterwegs‘ scheint rechtlich unverbindlich zu sein"] }, reaction: (position) => position === "first" ? "Schickt drei Korrekturen und speichert den Bericht dann heimlich." : position === "last" ? "Liest alles und antwortet mit einem Emoji." : "Bestreitet alles, bevor die Lieblingsstelle zitiert wird.", verdict: (chat) => `${chat} ist eine kleine Institution ohne Verfassung, mit inkonsistenten Öffnungszeiten und erstaunlicher Bindung. Das Chaos ist kein Fehler. Es ist Gruppenkultur.` },
  "pt-br": { ...en, titles: ["Gerente de projeto não oficial", "Diretor de reações", "Departamento de reviravoltas", "Diretor de sumiços estratégicos", "Guardião da história"], title: (chat) => `${chat}: um desastre lindamente organizado`, subtitle: "Uma leitura forense dos planos, sumiços e áudios totalmente desnecessários.", portrait: (name, share, first) => `${name} responde por ${share}% do chat e transformou isso em traço de personalidade em tempo integral. ${first ? "Se este grupo tem volante, esta pessoa está segurando." : "Talvez não comande o chat, mas o timing das entradas merece um estudo."}`, firstLine: "Não é controle. É preocupação legítima porque mais ninguém fez um plano.", otherLine: "Presente quando a trama precisa, misteriosamente offline quando chega a logística.", opening: (chat, top) => `${chat} se mantém com carinho, perguntas repetidas sem resposta e a recusa de ${top} em deixar um plano morrer em silêncio. Funciona. Ninguém sabe por quê, mas funciona.`, awards: (top, quiet, second) => [{ title: "Plano com maior chance de acontecer", winner: top, reason: "O volume diz liderança. As cobranças dizem cansaço leve." }, { title: "Melhor aparição surpresa", winner: quiet, reason: "Baixa frequência. Máximo impacto narrativo." }, { title: "Prêmio vitalício do ‘tô chegando’", winner: second, reason: "A comissão conferiu os horários. A comissão está preocupada." }], dictionary: [{ term: "A gente devia", meaning: "Nada vai acontecer sem uma segunda mensagem mais séria." }, { term: "Hahaha", meaning: "Recebido. Nenhuma providência será tomada." }, { term: "Tô chegando", meaning: "Uma declaração ampla de intenção futura." }], dynamics: (top) => [`${top} cria movimento; o resto cria textura.`, "Os planos passam por três fases emocionais antes do calendário.", "O silêncio costuma ser alguém preparando um emoji."], flags: { green: ["Vocês sempre voltam uns para os outros", "O grupo tem uma língua própria que ninguém de fora entenderia"], yellow: ["As perguntas viram peças arqueológicas", "A organização depende de uma pessoa suspeitamente competente"], red: ["‘Tô chegando’ parece não ter valor jurídico"] }, reaction: (position) => position === "first" ? "Vai mandar três correções e salvar o relatório em silêncio." : position === "last" ? "Vai ler tudo e responder com um emoji." : "Vai negar antes de citar a parte favorita.", verdict: (chat) => `${chat} é uma pequena instituição sem constituição, com horários inconsistentes e retenção excelente. O caos não é um bug. É a cultura do grupo.` },
  pt: { ...en, titles: ["Gestor de projeto não oficial", "Diretor de reações", "Departamento de reviravoltas", "Diretor de desaparecimentos estratégicos", "Guardião da história"], title: (chat) => `${chat}: um desastre lindamente organizado`, subtitle: "Uma leitura forense dos planos, desaparecimentos e áudios totalmente desnecessários.", portrait: (name, share, first) => `${name} responde por ${share}% da conversa e transformou isso num traço de personalidade a tempo inteiro. ${first ? "Se este grupo tem volante, esta pessoa segura-o." : "Pode não comandar a conversa, mas o timing das entradas merece um estudo."}`, firstLine: "Não é controlo. É preocupação legítima porque mais ninguém fez um plano.", otherLine: "Presente quando a trama precisa, misteriosamente offline quando chega a logística.", opening: (chat, top) => `${chat} mantém-se com carinho, perguntas repetidas sem resposta e a recusa de ${top} em deixar um plano morrer em silêncio. Funciona. Ninguém sabe porquê, mas funciona.`, awards: (top, quiet, second) => [{ title: "Plano com maior hipótese de acontecer", winner: top, reason: "O volume diz liderança. As insistências dizem ligeiro cansaço." }, { title: "Melhor aparição surpresa", winner: quiet, reason: "Baixa frequência. Máximo impacto narrativo." }, { title: "Prémio de carreira do «estou a chegar»", winner: second, reason: "O júri confirmou os horários. O júri está preocupado." }], dictionary: [{ term: "Devíamos", meaning: "Nada acontecerá sem uma segunda mensagem mais séria." }, { term: "Hahaha", meaning: "Recebido. Não haverá outra ação." }, { term: "Estou a chegar", meaning: "Uma declaração ampla de intenção futura." }], dynamics: (top) => [`${top} cria movimento; os restantes criam textura.`, "Os planos passam por três fases emocionais antes do calendário.", "O silêncio costuma ser alguém a preparar um emoji."], flags: { green: ["Continuam a voltar uns para os outros", "O grupo tem uma língua própria incompreensível para quem está fora"], yellow: ["As perguntas tornam-se peças arqueológicas", "A organização depende de uma pessoa suspeitosamente competente"], red: ["«Estou a chegar» parece não ter valor jurídico"] }, reaction: (position) => position === "first" ? "Vai enviar três correções e guardar o relatório em silêncio." : position === "last" ? "Vai ler tudo e responder com um emoji." : "Vai negar antes de citar a parte favorita.", verdict: (chat) => `${chat} é uma pequena instituição sem constituição, com horários inconsistentes e excelente retenção. O caos não é um erro. É a cultura do grupo.` },
  nl: { ...en, titles: ["Onofficiële projectmanager", "Hoofd reacties", "Afdeling plotwendingen", "Directeur strategisch verdwijnen", "Bewaker van de groepsgeschiedenis"], title: (chat) => `${chat}: een prachtig georganiseerd fiasco`, subtitle: "Een forensische lezing van plannen, verdwijningen en volstrekt onnodige spraakberichten.", portrait: (name, share, first) => `${name} levert ${share}% van de chat en heeft daar een fulltime karaktertrek van gemaakt. ${first ? "Als deze groep een stuur heeft, houdt deze persoon het vast." : "Deze persoon leidt de chat misschien niet, maar de timing van de optredens verdient onderzoek."}`, firstLine: "Niet bazig. Gewoon terecht bezorgd dat niemand anders een plan heeft gemaakt.", otherLine: "Aanwezig wanneer het verhaal dat nodig heeft, spoorloos zodra logistiek verschijnt.", opening: (chat, top) => `${chat} blijft bijeen door genegenheid, herhaalde onbeantwoorde vragen en ${top}s weigering om een plan stil te laten sterven. Het werkt. Niemand weet waarom, maar het werkt.`, awards: (top, quiet, second) => [{ title: "Plan met de grootste kans om echt te gebeuren", winner: top, reason: "Het berichtenaantal zegt leiderschap. De reminders zeggen lichte vermoeidheid." }, { title: "Beste verrassingsoptreden", winner: quiet, reason: "Lage frequentie. Maximale impact." }, { title: "Oeuvreprijs voor ‘ik ben onderweg’", winner: second, reason: "De jury controleerde de tijden. De jury maakt zich zorgen." }], dictionary: [{ term: "We zouden", meaning: "Dit gebeurt niet zonder een tweede, serieuzere boodschap." }, { term: "Hahaha", meaning: "Ontvangen. Er volgt geen verdere actie." }, { term: "Ik ben onderweg", meaning: "Een ruime verklaring van toekomstige intentie." }], dynamics: (top) => [`${top} maakt vaart; de rest zorgt voor sfeer.`, "Plannen doorlopen drie emotionele fasen voordat ze in een agenda komen.", "Stilte betekent meestal dat iemand een reactie-emoji voorbereidt."], flags: { green: ["Jullie komen steeds bij elkaar terug", "De groep heeft een eigen taal die buitenstaanders niet zouden overleven"], yellow: ["Vragen worden regelmatig archeologische vondsten", "De planning hangt af van één verdacht competente persoon"], red: ["‘Ik ben onderweg’ lijkt juridisch niet bindend"] }, reaction: (position) => position === "first" ? "Stuurt drie correcties en slaat het rapport daarna stilletjes op." : position === "last" ? "Leest alles en antwoordt met één emoji." : "Ontkent het voordat het favoriete stuk wordt geciteerd.", verdict: (chat) => `${chat} is een kleine instelling zonder grondwet, met inconsistente openingstijden en verrassend sterke binding. De chaos is geen fout. Het is de groepscultuur.` },
};

export function createFallbackReport(conversation: ParsedConversation, chatName: string, locale: string): RoastReport {
  const copy = copies[locale] ?? en;
  const top = conversation.participants[0]?.name ?? "Someone";
  const quiet = conversation.participants.at(-1)?.name ?? top;
  const participants = conversation.participants.map((participant, index) => ({
    ...participant,
    title: copy.titles[index % copy.titles.length],
    portrait: copy.portrait(participant.name, participant.share, index === 0),
    evidence: conversation.messages.filter((message) => message.author === participant.name && message.body.length > 12).slice(0, 2).map((message) => message.body.slice(0, 120)),
    finalLine: index === 0 ? copy.firstLine : copy.otherLine,
  }));
  return {
    id: randomUUID(), title: copy.title(chatName), subtitle: copy.subtitle, chatName, locale, createdAt: new Date().toISOString(),
    stats: { messageCount: conversation.messages.length, participantCount: conversation.participants.length, dateRange: formatDateRange(conversation.firstDate, conversation.lastDate, locale) },
    opening: copy.opening(chatName, top), participants,
    awards: copy.awards(top, quiet, participants[1]?.name ?? top), dictionary: copy.dictionary, dynamics: copy.dynamics(top), flags: copy.flags,
    reactions: participants.map((participant, index) => ({ name: participant.name, reaction: copy.reaction(index === 0 ? "first" : index === participants.length - 1 ? "last" : "middle") })),
    finalVerdict: copy.verdict(chatName),
  };
}
