import { isLocale, type Locale } from "@/i18n/config";

type ReportUi = {
  generatingTitle: string; generatingBody: string; failedTitle: string; failedBody: string; tryAgain: string;
  privateReport: string; share: string; copied: string; classic: string; messages: string; protagonists: string; calledOut: string;
  opening: string; cast: string; portraits: string; paywallTitle: string; paywallBody: string; features: string[];
  oneTime: string; privateDefault: string; unlock: string; awardsKicker: string; awardsTitle: string;
  dictionaryKicker: string; dictionaryTitle: string; dynamicsKicker: string; dynamicsTitle: string;
  flagsKicker: string; flagsTitle: string; finalKicker: string; shareGroup: string;
};

const en: ReportUi = {
  generatingTitle: "Roastin is reading between the lines.", generatingBody: "You can close this page. The report will keep cooking.", failedTitle: "Roastin dropped the notes.", failedBody: "The source chat has been deleted. Start again and we’ll take another pass.", tryAgain: "Try again",
  privateReport: "Private report", share: "Share", copied: "Link copied", classic: "The Classic Report", messages: "messages", protagonists: "protagonists", calledOut: "called out", opening: "Roastin’s opening notes", cast: "The cast", portraits: "Participant portraits",
  paywallTitle: "You’ve only seen the opening act.", paywallBody: "Unlock every portrait, the awards, your private dictionary, hidden dynamics, flags, predicted reactions and Roastin’s final verdict.", features: ["Every full portrait", "Group awards", "Private dictionary", "Hidden dynamics", "Red, yellow & green flags", "The final verdict"], oneTime: "one time", privateDefault: "No subscription. Private by default.", unlock: "Unlock the full report",
  awardsKicker: "Official recognition", awardsTitle: "The awards nobody applied for", dictionaryKicker: "Translation required", dictionaryTitle: "The private dictionary", dynamicsKicker: "The social physics", dynamicsTitle: "Hidden dynamics", flagsKicker: "Traffic lights", flagsTitle: "The flags", finalKicker: "Roastin’s final verdict", shareGroup: "Share with the group",
};

const copies: Record<Locale, ReportUi> = {
  en,
  fr: { ...en, generatingTitle: "Roastin lit entre les lignes.", generatingBody: "Tu peux fermer cette page. Le rapport continue de cuire.", failedTitle: "Roastin a fait tomber ses notes.", failedBody: "La conversation source a été supprimée. Recommence pour une nouvelle lecture.", tryAgain: "Réessayer", privateReport: "Rapport privé", share: "Partager", copied: "Lien copié", classic: "Le rapport Classic", protagonists: "protagonistes", calledOut: "démasqués", opening: "Les premières notes de Roastin", cast: "Le casting", portraits: "Portraits des participants", paywallTitle: "Tu n’as vu que la première partie.", paywallBody: "Débloque tous les portraits, les awards, votre dictionnaire privé, les dynamiques, les drapeaux, les réactions prédites et le verdict final.", features: ["Tous les portraits", "Awards du groupe", "Dictionnaire privé", "Dynamiques cachées", "Green, yellow et red flags", "Verdict final"], oneTime: "une fois", privateDefault: "Sans abonnement. Privé par défaut.", unlock: "Débloquer le rapport complet", awardsKicker: "Reconnaissance officielle", awardsTitle: "Les awards que personne n’a demandés", dictionaryKicker: "Traduction nécessaire", dictionaryTitle: "Le dictionnaire privé", dynamicsKicker: "Physique sociale", dynamicsTitle: "Dynamiques cachées", flagsKicker: "Feux de signalisation", flagsTitle: "Les drapeaux", finalKicker: "Le verdict final de Roastin", shareGroup: "Partager avec le groupe" },
  es: { ...en, generatingTitle: "Roastin está leyendo entre líneas.", generatingBody: "Puedes cerrar esta página. El informe seguirá cocinándose.", failedTitle: "Roastin perdió sus notas.", failedBody: "La conversación original se eliminó. Empieza de nuevo para intentarlo otra vez.", tryAgain: "Reintentar", privateReport: "Informe privado", share: "Compartir", copied: "Enlace copiado", classic: "Informe Classic", messages: "mensajes", protagonists: "protagonistas", calledOut: "retratados", opening: "Las primeras notas de Roastin", cast: "El reparto", portraits: "Retratos", paywallTitle: "Solo has visto el primer acto.", paywallBody: "Desbloquea todos los retratos, premios, diccionario privado, dinámicas, banderas, reacciones y veredicto final.", features: ["Todos los retratos", "Premios del grupo", "Diccionario privado", "Dinámicas ocultas", "Banderas verdes, amarillas y rojas", "Veredicto final"], oneTime: "pago único", privateDefault: "Sin suscripción. Privado por defecto.", unlock: "Desbloquear el informe completo", awardsKicker: "Reconocimiento oficial", awardsTitle: "Los premios que nadie solicitó", dictionaryKicker: "Hace falta traducción", dictionaryTitle: "El diccionario privado", dynamicsKicker: "Física social", dynamicsTitle: "Dinámicas ocultas", flagsKicker: "Semáforo", flagsTitle: "Las banderas", finalKicker: "Veredicto final de Roastin", shareGroup: "Compartir con el grupo" },
  it: { ...en, generatingTitle: "Roastin sta leggendo tra le righe.", generatingBody: "Puoi chiudere la pagina. Il report continuerà a cuocere.", failedTitle: "Roastin ha perso gli appunti.", failedBody: "La chat originale è stata eliminata. Ricomincia per riprovare.", tryAgain: "Riprova", privateReport: "Report privato", share: "Condividi", copied: "Link copiato", classic: "Report Classic", messages: "messaggi", protagonists: "protagonisti", calledOut: "smascherati", opening: "Gli appunti iniziali di Roastin", cast: "Il cast", portraits: "Ritratti dei partecipanti", paywallTitle: "Hai visto solo il primo atto.", paywallBody: "Sblocca tutti i ritratti, i premi, il dizionario privato, le dinamiche, le bandiere, le reazioni e il verdetto finale.", features: ["Tutti i ritratti", "Premi del gruppo", "Dizionario privato", "Dinamiche nascoste", "Bandiere verdi, gialle e rosse", "Verdetto finale"], oneTime: "una tantum", privateDefault: "Nessun abbonamento. Privato per impostazione predefinita.", unlock: "Sblocca il report completo", awardsKicker: "Riconoscimento ufficiale", awardsTitle: "I premi che nessuno ha richiesto", dictionaryKicker: "Traduzione necessaria", dictionaryTitle: "Il dizionario privato", dynamicsKicker: "Fisica sociale", dynamicsTitle: "Dinamiche nascoste", flagsKicker: "Semaforo", flagsTitle: "Le bandiere", finalKicker: "Il verdetto finale di Roastin", shareGroup: "Condividi con il gruppo" },
  de: { ...en, generatingTitle: "Roastin liest zwischen den Zeilen.", generatingBody: "Du kannst diese Seite schließen. Der Bericht wird weiter erstellt.", failedTitle: "Roastin hat seine Notizen fallen gelassen.", failedBody: "Der Quellchat wurde gelöscht. Starte neu für einen weiteren Versuch.", tryAgain: "Erneut versuchen", privateReport: "Privater Bericht", share: "Teilen", copied: "Link kopiert", classic: "Classic-Bericht", messages: "Nachrichten", protagonists: "Hauptfiguren", calledOut: "ertappt", opening: "Roastins erste Notizen", cast: "Die Besetzung", portraits: "Teilnehmerporträts", paywallTitle: "Du hast erst den Auftakt gesehen.", paywallBody: "Schalte alle Porträts, Awards, das private Wörterbuch, Dynamiken, Flaggen, Reaktionen und das Schlussurteil frei.", features: ["Alle Porträts", "Gruppen-Awards", "Privates Wörterbuch", "Verborgene Dynamiken", "Grüne, gelbe und rote Flaggen", "Schlussurteil"], oneTime: "einmalig", privateDefault: "Kein Abo. Standardmäßig privat.", unlock: "Vollständigen Bericht freischalten", awardsKicker: "Offizielle Anerkennung", awardsTitle: "Die Awards, für die sich niemand beworben hat", dictionaryKicker: "Übersetzung nötig", dictionaryTitle: "Das private Wörterbuch", dynamicsKicker: "Soziale Physik", dynamicsTitle: "Verborgene Dynamiken", flagsKicker: "Ampel", flagsTitle: "Die Flaggen", finalKicker: "Roastins Schlussurteil", shareGroup: "Mit der Gruppe teilen" },
  "pt-br": { ...en, generatingTitle: "Roastin está lendo nas entrelinhas.", generatingBody: "Você pode fechar esta página. O relatório continuará sendo preparado.", failedTitle: "Roastin perdeu as anotações.", failedBody: "A conversa original foi excluída. Comece novamente para tentar outra vez.", tryAgain: "Tentar novamente", privateReport: "Relatório privado", share: "Compartilhar", copied: "Link copiado", classic: "Relatório Classic", messages: "mensagens", protagonists: "protagonistas", calledOut: "expostos", opening: "As primeiras notas de Roastin", cast: "O elenco", portraits: "Retratos dos participantes", paywallTitle: "Você viu só o primeiro ato.", paywallBody: "Desbloqueie todos os retratos, prêmios, dicionário privado, dinâmicas, bandeiras, reações e veredito final.", features: ["Todos os retratos", "Prêmios do grupo", "Dicionário privado", "Dinâmicas ocultas", "Bandeiras verdes, amarelas e vermelhas", "Veredito final"], oneTime: "pagamento único", privateDefault: "Sem assinatura. Privado por padrão.", unlock: "Desbloquear o relatório completo", awardsKicker: "Reconhecimento oficial", awardsTitle: "Os prêmios que ninguém pediu", dictionaryKicker: "Tradução necessária", dictionaryTitle: "O dicionário privado", dynamicsKicker: "Física social", dynamicsTitle: "Dinâmicas ocultas", flagsKicker: "Semáforo", flagsTitle: "As bandeiras", finalKicker: "Veredito final de Roastin", shareGroup: "Compartilhar com o grupo" },
  pt: { ...en, generatingTitle: "Roastin está a ler nas entrelinhas.", generatingBody: "Podes fechar esta página. O relatório continuará a ser preparado.", failedTitle: "Roastin perdeu as notas.", failedBody: "A conversa original foi eliminada. Recomeça para tentar novamente.", tryAgain: "Tentar novamente", privateReport: "Relatório privado", share: "Partilhar", copied: "Ligação copiada", classic: "Relatório Classic", messages: "mensagens", protagonists: "protagonistas", calledOut: "expostos", opening: "As primeiras notas de Roastin", cast: "O elenco", portraits: "Retratos dos participantes", paywallTitle: "Viste apenas o primeiro ato.", paywallBody: "Desbloqueia todos os retratos, prémios, dicionário privado, dinâmicas, bandeiras, reações e veredito final.", features: ["Todos os retratos", "Prémios do grupo", "Dicionário privado", "Dinâmicas ocultas", "Bandeiras verdes, amarelas e vermelhas", "Veredito final"], oneTime: "pagamento único", privateDefault: "Sem subscrição. Privado por defeito.", unlock: "Desbloquear o relatório completo", awardsKicker: "Reconhecimento oficial", awardsTitle: "Os prémios que ninguém pediu", dictionaryKicker: "Tradução necessária", dictionaryTitle: "O dicionário privado", dynamicsKicker: "Física social", dynamicsTitle: "Dinâmicas ocultas", flagsKicker: "Semáforo", flagsTitle: "As bandeiras", finalKicker: "Veredito final de Roastin", shareGroup: "Partilhar com o grupo" },
  nl: { ...en, generatingTitle: "Roastin leest tussen de regels door.", generatingBody: "Je kunt deze pagina sluiten. Het rapport blijft doorgaan.", failedTitle: "Roastin liet zijn notities vallen.", failedBody: "De bronchat is verwijderd. Begin opnieuw voor een nieuwe poging.", tryAgain: "Opnieuw proberen", privateReport: "Privérapport", share: "Delen", copied: "Link gekopieerd", classic: "Classic-rapport", messages: "berichten", protagonists: "hoofdpersonen", calledOut: "ontmaskerd", opening: "Roastins eerste notities", cast: "De cast", portraits: "Portretten van deelnemers", paywallTitle: "Je hebt alleen de openingsact gezien.", paywallBody: "Ontgrendel alle portretten, awards, het privéwoordenboek, dynamieken, vlaggen, reacties en het eindoordeel.", features: ["Alle portretten", "Groepsawards", "Privéwoordenboek", "Verborgen dynamieken", "Groene, gele en rode vlaggen", "Eindoordeel"], oneTime: "eenmalig", privateDefault: "Geen abonnement. Standaard privé.", unlock: "Volledig rapport ontgrendelen", awardsKicker: "Officiële erkenning", awardsTitle: "De awards waarvoor niemand zich aanmeldde", dictionaryKicker: "Vertaling vereist", dictionaryTitle: "Het privéwoordenboek", dynamicsKicker: "Sociale fysica", dynamicsTitle: "Verborgen dynamieken", flagsKicker: "Verkeerslichten", flagsTitle: "De vlaggen", finalKicker: "Roastins eindoordeel", shareGroup: "Delen met de groep" },
};

export function reportUi(locale: string | null | undefined) {
  return copies[locale && isLocale(locale) ? locale : "en"];
}

export type { ReportUi };
