import en from "@/i18n/dictionaries/en";
import type { Dictionary } from "@/i18n/types";

const dictionary = {
  ...en,
  languageName: "Deutsch",
  common: { skipToContent: "Zum Inhalt", language: "Sprache", close: "Schließen", back: "Zurück", continue: "Weiter", createReport: "Meinen Chat roasten", myReports: "Meine Berichte", privacy: "Datenschutz", terms: "Bedingungen", help: "Hilfe", contact: "Kontakt", deleteData: "Meine Daten löschen", adultOnly: "Nur ab 18" },
  seo: { title: "Roastin Has Notes — Dein Gruppenchat, ungefiltert", description: "Lade einen WhatsApp-Chat hoch und erhalte einen privaten, witzigen und erstaunlich treffenden Bericht über eure Gruppendynamik." },
  nav: { how: "So funktioniert es", data: "Deine Daten", faq: "FAQ" },
  landing: { ...en.landing,
    eyebrow: "Der Gruppenchat-Bericht", titleBefore: "Dein Chat hat", titleAccent: "Geheimnisse.", titleAfter: "Roastin macht Notizen.", subtitle: "Lade einen WhatsApp-Chat hoch. Erhalte den ungefilterten, verdächtig treffenden Bericht, den niemand aus der Gruppe schreiben würde.", privacyNote: "Der Originalchat wird nach der Erstellung nicht aufbewahrt", trust: ["Kein Konto nötig", "Standardmäßig privat", "In Minuten fertig"], ticker: ["Niemand hat gefragt.", "Roastin hat geantwortet.", "Die Beweise sind da."],
    howEyebrow: "Lächerlich einfach", howTitle: "Vom Gruppenchat zum Hauptereignis", howText: "Keine Fragebögen, keine peinlichen Tests. Roastin nutzt, was eure Gruppe bereits gesagt hat.", steps: [{ title: "Beweise abgeben", text: "Exportiere den WhatsApp-Chat und lade die .txt- oder .zip-Datei hoch." }, { title: "Roastin macht Notizen", text: "Er erkennt wiederkehrende Muster und schreibt einen auf dem Chat basierenden Bericht." }, { title: "Lesen, staunen, teilen", text: "Erhalte Porträts, Awards, Insider und ein Urteil für eure Gruppe." }],
    reportEyebrow: "Ein Bericht, den nur dein Chat schreiben konnte", reportTitle: "Allgemeine Persönlichkeitstests können einpacken.", reportText: "Jede Beobachtung basiert auf sichtbaren Mustern: Wer plant, wer abtaucht und wer genau ein Reaktions-Emoji kennt.", features: ["Teilnehmerporträts", "Gruppen-Awards", "Privates Wörterbuch", "Versteckte Dynamiken", "Grüne, gelbe und rote Flaggen", "Vorhergesagte Reaktionen"],
    privacyEyebrow: "Dein Chat bleibt deiner", privacyTitle: "Der Tee ist heiß. Unser Rohchat-Speicher nicht.", privacyText: "Der Chat wird während der Erstellung verschlüsselt zwischengespeichert, nie in unserer Anwendungsdatenbank abgelegt und nach der Verarbeitung gelöscht.", privacyCards: [{ title: "Ein Zweck", text: "Der Chat wird zur Erstellung deines Berichts verwendet." }, { title: "Original nicht gespeichert", text: "Der Rohupload wird nach Ende der Anfrage verworfen." }, { title: "Bericht bleibt privat", text: "Der abgeleitete Bericht bleibt für dich gespeichert und kann gelöscht werden." }],
    faqEyebrow: "Bevor du den Klatsch abgibst", faqTitle: "Berechtigte Fragen.", faqs: [{ question: "Speichert ihr meinen Chat?", answer: "Den Originalexport speichern wir nicht in der Anwendungsdatenbank. Er wird für den Bericht verarbeitet und danach verworfen. Der abgeleitete Bericht bleibt privat, bis du ihn löschst." }, { question: "Erfahren die anderen davon?", answer: "Nur wenn du es ihnen sagst. Berichte sind privat; ein separater Teilungslink kann widerrufen werden." }, { question: "Ist das gemein?", answer: "Roastin zielt auf wiederholte Verhaltensweisen, nie auf Identität, Aussehen oder sensible Merkmale." }, { question: "Welche Chats funktionieren am besten?", answer: "Aktive Gruppen sind ideal, aber Paare, beste Freunde, Familien und Teams funktionieren ebenfalls." }], finalTitle: "Dein Gruppenchat hat das Material schon geschrieben.", finalText: "Roastin ist nur mutig genug, es laut zu sagen.", finalCta: "Beweise abgeben",
  },
  onboarding: { ...en.onboarding,
    step: "Schritt", of: "von", back: "Zurück", continue: "Weiter", close: "Schließen", errors: { format: "Wähle einen WhatsApp-.txt-Export oder das .zip-Archiv.", size: "Diese Beta akzeptiert Chats bis 2 MB.", archive: "Das Archiv enthält keinen lesbaren WhatsApp-Textexport.", short: "Nicht genug Nachrichten gefunden. Wähle einen unbearbeiteten WhatsApp-Export.", generation: "Der Bericht konnte nicht erstellt werden. Versuch es erneut." },
    types: { eyebrow: "Die Lage", title: "Mit welcher Art Chat haben wir es zu tun?", text: "Jede Gruppe hat eigene Naturgesetze. So kann Roastin die Stimmung lesen.", options: { friends: { label: "Freundesgruppe", detail: "Das schöne Chaos" }, partner: { label: "Partner oder Crush", detail: "Lesen auf eigene Gefahr" }, "best-friend": { label: "Beste Freunde", detail: "Eine Institution zu zweit" }, family: { label: "Familie", detail: "Generationenwissen inklusive" }, work: { label: "Arbeit oder Team", detail: "Professionell unprofessionell" }, other: { label: "Etwas anderes", detail: "Roastin findet es heraus" } } },
    context: { eyebrow: "Optionaler Kontext", title: "Sollte Roastin etwas wissen?", text: "Ein Satz reicht. Überspringe, wenn die Nachrichten für sich sprechen.", placeholder: "Wir kennen uns seit der Uni und jede Reiseplanung wird zu sechs Wochen Verhandlung…" },
    upload: { eyebrow: "Die Beweise", title: "Lade deinen WhatsApp-Export hoch.", text: "Wähle die .txt- oder .zip-Datei eines Exports ohne Medien. Die erste Analyse erfolgt im Browser.", choose: ".txt- oder .zip-Datei wählen", limits: "Maximal 2 MB · Keine Medien", messages: "Nachrichten", participants: "Teilnehmende", replace: "Andere Datei wählen", privacy: "Originalchat nach Erstellung verworfen", sample: "Beispielchat ausprobieren" },
    review: { eyebrow: "Besetzung", title: "Prüfe, ob wir die Runde verstanden haben.", text: "Nutze Vornamen oder Spitznamen. Sie erscheinen im Bericht.", chatName: "Chatname" },
    launch: { ready: "Roastin ist bereit für", messages: "Nachrichten", protagonists: "Hauptfiguren", warning: "Sie ahnen nicht, was sie gleich erfahren.", cards: ["Muster", "Porträts", "Urteil"], consent: "Ich bestätige, mindestens 18 zu sein, dass der Chat keine Minderjährigen betrifft, und stimme der vorübergehenden Verarbeitung zur Berichtserstellung zu.", loading: "Zwischen den Zeilen lesen. Das kann eine Minute dauern…", cta: "Roastin loslegen lassen" },
  },
  pages: {
    privacy: { eyebrow: "Datenschutz", title: "Was wir verarbeiten, speichern und löschen", intro: "Diese verständliche Erklärung beschreibt den heutigen Produktstand. Sie behauptet nicht, dass wir nichts speichern.", sections: [
      { title: "Der Originalchat", paragraphs: ["Der Browser liest den Export lokal für die erste Zusammenfassung. Bei der Berichtsanfrage wird er per HTTPS übertragen, von offensichtlichen E-Mails und Telefonnummern bereinigt und im Arbeitsspeicher unseres Servers sowie des konfigurierten KI-Anbieters verarbeitet.", "Export und Transkript werden nicht in unsere Datenbank geschrieben und nach Ende der Anfrage verworfen. Wir weisen den KI-Anbieter an, keine Daten zu sammeln; seine eigenen Bedingungen gelten dennoch."] },
      { title: "Was wir speichern", paragraphs: ["Wir speichern den abgeleiteten Bericht und die Vorschau, Chatname, Sprache, aggregierte Zähler, Zeitpunkte, Modellkennung und den Abschluss der Rohdatenverarbeitung."], bullets: ["Anonymes Eigentümer-Token als Server-Hash", "E-Mail und kurzlebige Codes bei Konten", "Stripe-Zahlungsreferenzen", "Widerrufbare Links", "Für WhatsApp: verschlüsselte Nummer, Blindindex, Einwilligung, Vorlage, Anbieter-ID und Status"] },
      { title: "Zwecke und Dauer", paragraphs: ["Wir nutzen Daten zur Bereitstellung und Absicherung, für Käufe, Missbrauchsschutz und Pflichten. Berichte bleiben bis zur Löschung; Sitzungen laufen 30 Tage, Lieferlinks 7 Tage."], bullets: ["Eine endgültige Frist für verschlüsselte WhatsApp-Nummern fehlt noch; sie kann sofort entfernt werden.", "Logs sollen keine Chatnachrichten enthalten; Anbieter können technische Metadaten speichern."] },
      { title: "Deine Möglichkeiten", paragraphs: ["Du kannst Berichte löschen, Links widerrufen und WhatsApp-Daten entfernen. Für Auskunft, Berichtigung, Export oder Kontolöschung nutze Kontakt. Gesetzlich erforderliche Zahlungsdaten können bleiben."] },
      { title: "Anbieter und Startstatus", paragraphs: ["Je nach Funktion verarbeiten Hosting, Datenbank, OpenRouter und Modellanbieter, Stripe, E-Mail-Anbieter und Meta Daten. Verantwortliche Stelle, Adresse, Rechtsgrundlagen, Transfers und Aufbewahrungsplan müssen vor Start rechtlich geklärt werden, ebenso Daten von Nichtnutzern."] },
    ] },
    terms: { eyebrow: "Bedingungen", title: "Regeln für Roastin", intro: "Diese Beta-Bedingungen erklären Grenzen. Endgültige Firmen- und Rechtsangaben fehlen noch.", sections: [{ title: "Wer darf es nutzen", paragraphs: ["Du musst mindestens 18 sein. Lade keine Chats mit Minderjährigen hoch und stelle Rechtsgrundlage und erforderliche Erlaubnisse sicher."] }, { title: "Zulässige Nutzung", paragraphs: ["Nicht für Belästigung, Drohung, Diskriminierung, Offenlegung von Kontaktdaten, wichtige Entscheidungen oder illegale Inhalte nutzen. Keine Zugriffskontrollen umgehen."] }, { title: "Der Bericht", paragraphs: ["Automatisierte Unterhaltung aus sichtbaren Mustern; Fehler sind möglich. Keine psychologische, medizinische, rechtliche, berufliche oder Beziehungsberatung. Vor dem Teilen prüfen."] }, { title: "Käufe", paragraphs: ["Ein Bericht ist ein einmaliger Digitalkauf über Stripe. Preis und Währung im Checkout gelten. Erstattung, Widerruf und Steuern müssen je Markt geklärt werden."] }, { title: "Verfügbarkeit", paragraphs: ["Die Beta kann sich ändern oder ausfallen. Unabdingbare Rechte bleiben. Anwendbares Recht und Streitregeln brauchen juristische Prüfung."] }] },
    help: { eyebrow: "Hilfe", title: "Sauberer Export, besserer Bericht", intro: "Schnelle Antworten zu Import, Datenschutz, Zugriff und Teilen.", sections: [{ title: "Aus WhatsApp exportieren", paragraphs: ["Chat öffnen, Chat exportieren, Ohne Medien wählen und .txt oder .zip hochladen. Grenze: 2 MB."] }, { title: "Importprobleme", paragraphs: ["Nutze einen originalen Textexport mit mindestens zwei Personen und acht Nachrichten. Keine Screenshots, PDFs oder Medienarchive."] }, { title: "Datenschutz und Sicherheit", paragraphs: ["Das Original wird nicht in unserer Datenbank gespeichert. Berichte sind privat. Chats mit erkennbaren Minderjährigen werden abgelehnt; offensichtliche Kontaktdaten vor der KI entfernt."] }, { title: "Zugriff und Teilen", paragraphs: ["Nutze denselben Browser oder die Zahlungs-E-Mail. Bezahlte Berichte haben widerrufbare Links. WhatsApp ist optional und einwilligungspflichtig."] }] },
    contact: { eyebrow: "Kontakt", title: "Mit einem Menschen sprechen", intro: "Für Hilfe, Datenschutz oder Sicherheit schreibe uns, ohne Chat-Inhalte mitzuschicken.", sections: [{ title: "Support", paragraphs: ["Schreibe an support@roastinhasnotes.com mit Berichts-ID, ggf. Zahlungs-E-Mail und kurzer Beschreibung. Export nicht anhängen."] }, { title: "Datenschutz", paragraphs: ["Betreff „Datenschutzanfrage“. Wir können Eigentum prüfen. Offizielle Frist und Verantwortlichenkontakt werden vor Start bestätigt."] }, { title: "Sicherheit", paragraphs: ["Betreff „Sicherheitsmeldung“. Das Postfach muss vor Start eingerichtet und überwacht werden."] }] },
    delete: { eyebrow: "Daten löschen", title: "Bericht oder Lieferdaten entfernen", intro: "Berichte lassen sich auf ihrer privaten Seite löschen. Kontoweite Löschung braucht in der Beta noch eine verifizierte Anfrage.", sections: [{ title: "Bericht löschen", paragraphs: ["Im besitzenden Browser oder Konto öffnen und Löschen wählen. Inhalt und Vorschau werden geleert, Links funktionieren nicht mehr. Zahlungsspuren können gesetzlich nötig bleiben."] }, { title: "WhatsApp-Nummer entfernen", paragraphs: ["Im bezahlten Bericht Lieferdaten entfernen. Verschlüsselte Nummer und Blindindex werden gelöscht, Lieferlinks widerrufen."] }, { title: "Konto löschen", paragraphs: ["Schreibe an support@roastinhasnotes.com mit Betreff „Löschanfrage“, ohne Chat. Wir prüfen das Eigentum. Automatische Kontolöschung ist noch nicht umgesetzt."] }] },
  },
} satisfies Dictionary;

export default dictionary;
