import en from "@/i18n/dictionaries/en";
import type { Dictionary } from "@/i18n/types";

const dictionary = {
  ...en,
  languageName: "Español",
  common: { skipToContent: "Ir al contenido", language: "Idioma", close: "Cerrar", back: "Atrás", continue: "Continuar", createReport: "Roastear mi chat", myReports: "Mis informes", privacy: "Privacidad", terms: "Condiciones", help: "Ayuda", contact: "Contacto", deleteData: "Eliminar mis datos", adultOnly: "Solo mayores de 18" },
  seo: { title: "Roastin Has Notes — Tu chat, sin filtros", description: "Sube una conversación de WhatsApp y recibe un informe privado, divertido y extrañamente preciso sobre tu grupo." },
  nav: { how: "Cómo funciona", data: "Tus datos", faq: "Preguntas" },
  landing: { ...en.landing,
    eyebrow: "El informe del chat", titleBefore: "Tu chat tiene", titleAccent: "secretos.", titleAfter: "Roastin toma nota.", subtitle: "Sube una conversación de WhatsApp. Recibe el informe sin filtros y sospechosamente preciso que nadie del grupo se atrevería a escribir.", privacyNote: "El chat original no se conserva después de generar el informe", trust: ["Sin cuenta", "Privado por defecto", "Listo en minutos"], ticker: ["Nadie preguntó.", "Roastin respondió.", "Aquí están las pruebas."],
    howEyebrow: "Ridículamente fácil", howTitle: "Del chat al gran evento", howText: "Sin cuestionarios ni tests incómodos. Roastin trabaja con lo que el grupo ya dijo.", steps: [{ title: "Suelta las pruebas", text: "Exporta tu chat de WhatsApp y sube el archivo .txt o .zip." }, { title: "Roastin toma nota", text: "Detecta patrones repetidos y escribe un informe basado en la conversación." }, { title: "Lee, alucina, comparte", text: "Recibe retratos, premios, bromas internas y un veredicto hecho para tu grupo." }],
    reportEyebrow: "Un informe que solo tu chat podía crear", reportTitle: "Los tests de personalidad genéricos no pueden competir.", reportText: "Cada observación parte de patrones visibles: quién propone planes, quién desaparece y quién solo usa un emoji.", features: ["Retratos de participantes", "Premios del grupo", "Diccionario privado", "Dinámicas ocultas", "Banderas verdes, amarillas y rojas", "Reacciones previstas"],
    privacyEyebrow: "Tu chat sigue siendo tuyo", privacyTitle: "El cotilleo quema. Nuestro almacenamiento del chat original, no.", privacyText: "La conversación se cifra temporalmente durante la generación, nunca se guarda en la base de datos de la aplicación y se elimina al terminar el proceso.", privacyCards: [{ title: "Un solo fin", text: "La conversación se usa para generar tu informe." }, { title: "Original no conservado", text: "El archivo original se descarta al terminar la solicitud." }, { title: "Informe privado", text: "El informe derivado se guarda para que puedas volver y eliminarlo." }],
    faqEyebrow: "Antes de soltar el cotilleo", faqTitle: "Preguntas justas.", faqs: [{ question: "¿Guardáis mi conversación?", answer: "No guardamos el archivo original en nuestra base de datos. Se procesa para crear el informe y después se descarta. El informe derivado sigue privado hasta que lo elimines." }, { question: "¿Se enterará la gente del chat?", answer: "Solo si se lo cuentas. Los informes son privados por defecto y el enlace de compartir se puede revocar." }, { question: "¿Es cruel?", answer: "Roastin se fija en conductas repetidas y hábitos, nunca en la identidad, el aspecto ni rasgos sensibles." }, { question: "¿Qué chats funcionan mejor?", answer: "Los grupos activos con varias personas son ideales, pero parejas, mejores amigos, familias y equipos también funcionan." }], finalTitle: "Tu grupo ya escribió el material.", finalText: "Roastin solo se atreve a decirlo en voz alta.", finalCta: "Suelta las pruebas",
  },
  onboarding: { ...en.onboarding,
    step: "Paso", of: "de", back: "Atrás", continue: "Continuar", close: "Cerrar",
    errors: { format: "Elige una exportación .txt de WhatsApp o su archivo .zip.", size: "Esta beta acepta conversaciones de hasta 2 MB.", archive: "El archivo no contiene una exportación de texto de WhatsApp legible.", short: "No encontramos suficientes mensajes. Elige una exportación original de WhatsApp.", generation: "No se pudo crear el informe. Inténtalo de nuevo." },
    types: { eyebrow: "Sitúanos", title: "¿Qué tipo de chat tenemos delante?", text: "Cada grupo tiene sus propias leyes. Esto ayuda a Roastin a captar el ambiente.", options: { friends: { label: "Grupo de amigos", detail: "El caos precioso" }, partner: { label: "Pareja o crush", detail: "Lee bajo tu responsabilidad" }, "best-friend": { label: "Mejor amigo", detail: "Una institución de dos" }, family: { label: "Familia", detail: "Historia generacional incluida" }, work: { label: "Trabajo o equipo", detail: "Profesionalmente poco profesional" }, other: { label: "Otra cosa", detail: "Roastin lo entenderá" } } },
    context: { eyebrow: "Contexto opcional", title: "¿Algo que Roastin deba saber?", text: "Una frase basta. Omítelo si los mensajes hablan solos.", placeholder: "Nos conocemos desde la universidad y cada viaje acaba en seis semanas de negociación…" },
    upload: { eyebrow: "Las pruebas", title: "Suelta tu exportación de WhatsApp.", text: "Elige el .txt o .zip de una exportación sin archivos multimedia. El análisis inicial ocurre en tu navegador.", choose: "Elegir archivo .txt o .zip", limits: "Máximo 2 MB · Sin multimedia", messages: "mensajes", participants: "participantes", replace: "Elegir otro archivo", privacy: "Chat original descartado tras la generación", sample: "Probar el chat de ejemplo" },
    review: { eyebrow: "Reparto", title: "Comprueba que entendimos el grupo.", text: "Usa nombres o apodos. Aparecerán así en el informe.", chatName: "Nombre del chat" },
    launch: { ready: "Roastin está listo para", messages: "mensajes", protagonists: "protagonistas", warning: "No tienen ni idea de lo que van a descubrir.", cards: ["Patrones", "Retratos", "Veredicto"], consent: "Confirmo que tengo 18 años o más, que la conversación no incluye menores y que consiento su tratamiento temporal para crear el informe.", loading: "Leyendo entre líneas. Puede tardar un minuto…", cta: "Que cocine Roastin" },
  },
  pages: {
    privacy: { eyebrow: "Privacidad", title: "Qué tratamos, conservamos y eliminamos", intro: "Este aviso describe con claridad cómo funciona hoy el producto. No afirma que no guardemos nada.", sections: [
      { title: "La conversación original", paragraphs: ["El navegador lee la exportación localmente para el resumen inicial. Al pedir el informe, la conversación viaja por HTTPS, se limpian emails y teléfonos evidentes y se procesa en memoria en nuestro servidor y el proveedor de IA configurado.", "El archivo original y la transcripción no se escriben en nuestra base de datos y se descartan al acabar la solicitud. Pedimos al proveedor de IA que no recopile esos datos, aunque siguen aplicando sus propias condiciones."] },
      { title: "Qué conservamos", paragraphs: ["Guardamos el informe derivado y su vista previa, nombre del chat, idioma, totales agregados, fechas, identificador del modelo y constancia de que terminó el tratamiento original."], bullets: ["Token anónimo de propiedad, con hash en el servidor", "Email y códigos temporales si creas una cuenta", "Referencias de pago de Stripe", "Enlaces revocables", "Para WhatsApp: número cifrado, huella, consentimiento, plantilla, identificador y estado"] },
      { title: "Finalidad y duración", paragraphs: ["Usamos estos datos para prestar y proteger el servicio, completar compras, prevenir abusos y cumplir deberes legales. Los informes permanecen hasta que los eliminas. Las sesiones duran 30 días y los enlaces de entrega 7 días."], bullets: ["Aún no existe un plazo final para los números cifrados de WhatsApp; puedes retirarlos de inmediato desde el informe.", "Los logs no deben contener mensajes, aunque los proveedores pueden conservar metadatos técnicos según sus políticas."] },
      { title: "Tus opciones", paragraphs: ["Puedes eliminar informes, revocar enlaces y borrar datos de entrega. Para acceso, rectificación, exportación o borrado de cuenta, usa Contacto. Algunos datos de transacción pueden conservarse por obligación legal."] },
      { title: "Proveedores", paragraphs: ["Según las funciones activas, intervienen alojamiento, base de datos, OpenRouter y el modelo elegido, Stripe, email y Meta para entregas solicitadas. Sus ubicaciones y garantías deben documentarse antes del lanzamiento."] },
      { title: "Estado previo al lanzamiento", paragraphs: ["Aún faltan la entidad responsable, dirección, contacto de privacidad, bases jurídicas por país y calendario definitivo. El servicio no está jurídicamente listo hasta completar la revisión, incluido el tratamiento de participantes no usuarios."] },
    ] },
    terms: { eyebrow: "Condiciones", title: "Reglas de uso de Roastin", intro: "Estas condiciones de beta explican los límites. Faltan los datos finales de empresa y jurisdicción antes del lanzamiento comercial.", sections: [
      { title: "Quién puede usarlo", paragraphs: ["Debes tener al menos 18 años. No subas conversaciones con menores. Debes contar con una base legal y los permisos necesarios para tratar y compartir la conversación."] },
      { title: "Uso aceptable", paragraphs: ["No uses Roastin para acosar, amenazar, discriminar, revelar datos de contacto, tomar decisiones importantes ni analizar contenido ilegal. No eludas controles de acceso."] },
      { title: "El informe", paragraphs: ["Es entretenimiento automatizado basado en patrones visibles. Puede equivocarse y no es asesoramiento psicológico, médico, jurídico, laboral ni sentimental. Revísalo antes de compartir."] },
      { title: "Compras", paragraphs: ["El informe es una compra digital única a través de Stripe. Se aplican precio y moneda mostrados. Reembolsos, desistimiento e impuestos deben cerrarse por mercado antes de vender al público."] },
      { title: "Disponibilidad y responsabilidad", paragraphs: ["La beta puede cambiar, fallar o retirarse. Nada excluye derechos o responsabilidades que la ley no permita excluir. Derecho aplicable y disputas siguen pendientes de revisión."] },
    ] },
    help: { eyebrow: "Ayuda", title: "Una exportación limpia, un informe mejor", intro: "Respuestas rápidas sobre importación, privacidad, acceso y uso compartido.", sections: [{ title: "Exportar desde WhatsApp", paragraphs: ["Abre el chat, elige Exportar chat, selecciona Sin archivos y sube el .txt o .zip. El límite actual es 2 MB."] }, { title: "Problemas de importación", paragraphs: ["Usa un texto original con al menos dos participantes y ocho mensajes. No subas capturas, PDF ni archivos multimedia."] }, { title: "Privacidad y seguridad", paragraphs: ["No guardamos el archivo original en nuestra base. Los informes son privados. Rechazamos chats que parecen incluir menores y ocultamos emails y teléfonos evidentes antes de la IA."] }, { title: "Acceso y compartir", paragraphs: ["Usa el mismo navegador o entra con el email de pago. Los informes pagados crean enlaces revocables. WhatsApp es opcional y requiere consentimiento."] }] },
    contact: { eyebrow: "Contacto", title: "Habla con una persona", intro: "Para soporte, privacidad o seguridad, escribe sin incluir contenido del chat.", sections: [{ title: "Soporte", paragraphs: ["Escribe a support@roastinhasnotes.com con el ID del informe, el email de pago si procede y una descripción breve. No adjuntes el chat."] }, { title: "Privacidad", paragraphs: ["Usa el asunto “Solicitud de privacidad”. Podemos verificar que controlas el informe o la cuenta. El plazo oficial y contacto responsable se confirmarán antes del lanzamiento."] }, { title: "Seguridad", paragraphs: ["Usa el asunto “Informe de seguridad”. El buzón debe estar provisionado y supervisado antes del lanzamiento."] }] },
    delete: { eyebrow: "Eliminar datos", title: "Elimina tu informe o datos de entrega", intro: "Puedes borrar el informe desde su página privada. El borrado completo de cuenta aún requiere una solicitud verificada.", sections: [{ title: "Eliminar un informe", paragraphs: ["Abre el informe con el navegador o cuenta propietaria y elige Eliminar. Se vacían contenido y vista previa y dejan de funcionar los enlaces. Pueden quedar datos de pago exigidos por ley."] }, { title: "Eliminar un número de WhatsApp", paragraphs: ["Desde el informe pagado, elimina los datos de entrega. Se borran el número cifrado y su huella y se revocan los enlaces."] }, { title: "Eliminar una cuenta", paragraphs: ["Escribe a support@roastinhasnotes.com con el asunto “Solicitud de eliminación”, sin enviar la conversación. Verificaremos la propiedad. El borrado automático de cuenta aún no existe."] }] },
  },
} satisfies Dictionary;

export default dictionary;
