import en from "@/i18n/dictionaries/en";
import type { Dictionary } from "@/i18n/types";

const dictionary = {
  ...en,
  languageName: "Italiano",
  common: { skipToContent: "Vai al contenuto", language: "Lingua", close: "Chiudi", back: "Indietro", continue: "Continua", createReport: "Fai il roast della chat", myReports: "I miei report", privacy: "Privacy", terms: "Termini", help: "Aiuto", contact: "Contatti", deleteData: "Elimina i miei dati", adultOnly: "Solo 18+" },
  seo: { title: "Roastin Has Notes — La tua chat, senza filtri", description: "Carica una conversazione WhatsApp e ricevi un report privato, divertente e stranamente preciso sul tuo gruppo." },
  nav: { how: "Come funziona", data: "I tuoi dati", faq: "FAQ" },
  landing: { ...en.landing,
    eyebrow: "Il report della chat", titleBefore: "La tua chat ha dei", titleAccent: "segreti.", titleAfter: "Roastin prende appunti.", subtitle: "Carica una conversazione WhatsApp. Ricevi il report senza filtri e stranamente accurato che nessuno nel gruppo oserebbe scrivere.", privacyNote: "La chat originale non viene conservata dopo la generazione", trust: ["Verificato via WhatsApp", "Privato per impostazione predefinita", "Pronto in pochi minuti"], ticker: ["Nessuno l’ha chiesto.", "Roastin ha risposto.", "Le prove ci sono."],
    howEyebrow: "Assurdamente facile", howTitle: "Dalla chat all’evento principale", howText: "Niente questionari o test imbarazzanti. Roastin usa ciò che il gruppo ha già detto.", steps: [{ title: "Carica le prove", text: "Esporta la chat WhatsApp e carica il file .txt o .zip." }, { title: "Roastin prende appunti", text: "Individua gli schemi ricorrenti e scrive un report basato sulla conversazione." }, { title: "Leggi, stupisciti, condividi", text: "Ottieni ritratti, premi, battute interne e un verdetto su misura." }],
    reportEyebrow: "Un report che solo la tua chat poteva creare", reportTitle: "I test di personalità generici non reggono il confronto.", reportText: "Ogni osservazione nasce da schemi visibili: chi propone, chi sparisce e chi usa sempre la stessa emoji.", features: ["Ritratti dei partecipanti", "Premi del gruppo", "Dizionario privato", "Dinamiche nascoste", "Bandiere verdi, gialle e rosse", "Reazioni previste"],
    privacyEyebrow: "La chat resta tua", privacyTitle: "Il gossip scotta. Il nostro archivio della chat originale no.", privacyText: "La conversazione viene cifrata in un archivio temporaneo durante la generazione, non viene mai salvata nel database dell’applicazione e viene eliminata al termine.", privacyCards: [{ title: "Un solo scopo", text: "La conversazione viene usata per generare il report." }, { title: "Originale non conservato", text: "Il file originale viene scartato al termine della richiesta." }, { title: "Report privato", text: "Il report derivato viene conservato per permetterti di ritrovarlo ed eliminarlo." }],
    faqEyebrow: "Prima di consegnare il gossip", faqTitle: "Domande legittime.", faqs: [{ question: "Conservate la conversazione?", answer: "Non salviamo l’esportazione originale nel database. Viene elaborata per creare il report e poi scartata. Il report derivato resta privato finché non lo elimini." }, { question: "Gli altri lo sapranno?", answer: "Solo se glielo dici. I report sono privati e il link separato di condivisione può essere revocato." }, { question: "È cattivo?", answer: "Roastin prende di mira comportamenti ripetuti, mai identità, aspetto o caratteristiche sensibili." }, { question: "Quali chat funzionano meglio?", answer: "I gruppi attivi sono ideali, ma funzionano anche coppie, migliori amici, famiglie e team." }], finalTitle: "La tua chat ha già scritto il materiale.", finalText: "Roastin ha solo il coraggio di dirlo ad alta voce.", finalCta: "Carica le prove",
  },
  onboarding: { ...en.onboarding,
    step: "Passaggio", of: "di", back: "Indietro", continue: "Continua", close: "Chiudi", errors: { format: "Scegli un’esportazione WhatsApp .txt o il relativo archivio .zip.", size: "Questa beta accetta conversazioni fino a 2 MB.", archive: "L’archivio non contiene un file di testo WhatsApp leggibile.", short: "Non abbiamo trovato abbastanza messaggi. Scegli un’esportazione WhatsApp non modificata.", generation: "Impossibile creare il report. Riprova." },
    types: { eyebrow: "Imposta la scena", title: "Con che tipo di chat abbiamo a che fare?", text: "Ogni gruppo ha le sue leggi. Questo aiuta Roastin a capire l’atmosfera.", options: { friends: { label: "Gruppo di amici", detail: "Il caos meraviglioso" }, partner: { label: "Partner o crush", detail: "Leggi a tuo rischio" }, "best-friend": { label: "Migliore amico", detail: "Un’istituzione per due" }, family: { label: "Famiglia", detail: "Tradizione generazionale inclusa" }, work: { label: "Lavoro o team", detail: "Professionalmente poco professionale" }, other: { label: "Altro", detail: "Roastin capirà" } } },
    context: { eyebrow: "Contesto facoltativo", title: "C’è qualcosa che Roastin dovrebbe sapere?", text: "Basta una frase. Salta se i messaggi parlano da soli.", placeholder: "Ci conosciamo dall’università e ogni vacanza diventa una trattativa di sei settimane…" },
    upload: { eyebrow: "Le prove", title: "Carica l’esportazione WhatsApp.", text: "Scegli il .txt o .zip di un’esportazione senza media. La prima analisi avviene nel browser.", choose: "Scegli il file .txt o .zip", limits: "Massimo 2 MB · Senza media", messages: "messaggi", participants: "partecipanti", replace: "Scegli un altro file", privacy: "Chat originale scartata dopo la generazione", sample: "Prova la chat di esempio" },
    review: { eyebrow: "Personaggi", title: "Controlla che abbiamo capito il gruppo.", text: "Usa nomi o soprannomi. Saranno mostrati nel report.", chatName: "Nome della chat" },
    launch: { ready: "Roastin è pronto per", messages: "messaggi", protagonists: "protagonisti", warning: "Non hanno idea di cosa stanno per scoprire.", cards: ["Schemi", "Ritratti", "Verdetto"], consent: "Confermo di avere almeno 18 anni, che la conversazione non coinvolge minori e acconsento al trattamento temporaneo per creare il report.", loading: "Lettura tra le righe. Potrebbe volerci un minuto…", cta: "Lascia cucinare Roastin" },
  },
  pages: {
    privacy: { eyebrow: "Privacy", title: "Cosa elaboriamo, conserviamo ed eliminiamo", intro: "Questa informativa descrive il prodotto come funziona oggi. Non afferma che non conserviamo nulla.", sections: [
      { title: "Conversazione originale", paragraphs: ["Il browser legge localmente l’esportazione per il riepilogo iniziale. Quando richiedi il report, la conversazione viaggia via HTTPS, email e telefoni evidenti vengono rimossi e il contenuto viene elaborato in memoria dal server e dal provider IA.", "L’esportazione e la trascrizione non sono scritte nel database e vengono scartate al termine della richiesta. Chiediamo al provider IA di non raccogliere i dati, ma si applicano comunque le sue condizioni."] },
      { title: "Cosa conserviamo", paragraphs: ["Conserviamo report derivato e anteprima, nome, lingua, conteggi aggregati, date, modello e prova della fine dell’elaborazione."], bullets: ["Token di sessione temporaneo con hash", "Numero WhatsApp verificato e cifrato, impronta, consenso e codici temporanei", "Riferimenti Stripe", "Link di condivisione e consegna revocabili", "Template WhatsApp, ID del provider e stato di consegna"] },
      { title: "Scopo e durata", paragraphs: ["I dati servono a fornire e proteggere il servizio, completare acquisti, prevenire abusi e rispettare obblighi. I report restano finché non li elimini; le sessioni durano 30 giorni e i link di consegna 7 giorni."], bullets: ["La durata finale dei numeri WhatsApp cifrati non è ancora configurata; puoi rimuoverli subito.", "I log non devono contenere messaggi, ma i fornitori possono conservare metadati tecnici."] },
      { title: "Le tue scelte", paragraphs: ["Puoi eliminare report, revocare link e rimuovere dati WhatsApp. Per accesso, rettifica, esportazione o eliminazione dell’account usa Contatti. Alcuni dati di pagamento possono restare per legge."] },
      { title: "Fornitori e stato di lancio", paragraphs: ["Possono intervenire hosting, database, OpenRouter e modello scelto, Stripe e Meta per autenticazione e consegna transazionale via WhatsApp. Responsabile, indirizzo, basi giuridiche, trasferimenti e tempi definitivi devono essere completati e verificati legalmente prima del lancio, incluso il trattamento dei non utenti."] },
    ] },
    terms: { eyebrow: "Termini", title: "Regole per usare Roastin", intro: "Questi termini beta spiegano i limiti; dettagli societari e giurisdizione sono ancora necessari.", sections: [{ title: "Chi può usarlo", paragraphs: ["Devi avere almeno 18 anni. Non caricare conversazioni con minori e assicurati di avere base legale e permessi necessari."] }, { title: "Uso accettabile", paragraphs: ["Non usare Roastin per molestie, minacce, discriminazioni, esposizione di contatti, decisioni importanti o contenuti illegali. Non aggirare i controlli."] }, { title: "Il report", paragraphs: ["È intrattenimento automatizzato e può sbagliare. Non è consulenza psicologica, medica, legale, lavorativa o relazionale. Rileggi prima di condividere."] }, { title: "Acquisti", paragraphs: ["Il report è un acquisto digitale una tantum tramite Stripe. Si applicano prezzo e valuta mostrati. Rimborsi, recesso e imposte vanno definiti per ogni mercato."] }, { title: "Disponibilità", paragraphs: ["La beta può cambiare o interrompersi. Restano validi i diritti inderogabili. Legge applicabile e controversie attendono revisione legale."] }] },
    help: { eyebrow: "Aiuto", title: "Un’esportazione pulita, un report migliore", intro: "Risposte rapide su importazione, privacy, accesso e condivisione.", sections: [{ title: "Esporta da WhatsApp", paragraphs: ["Apri la chat, scegli Esporta chat, Senza media e carica il .txt o .zip. Limite: 2 MB."] }, { title: "Problemi di importazione", paragraphs: ["Usa un testo originale con almeno due partecipanti e otto messaggi. Niente screenshot, PDF o archivi media."] }, { title: "Privacy e sicurezza", paragraphs: ["L’originale non viene salvato nel database. I report sono privati. Rifiutiamo chat con possibili minori e rimuoviamo contatti evidenti prima dell’IA."] }, { title: "Accesso e condivisione", paragraphs: ["Accedi con il numero WhatsApp verificato. Dopo il pagamento il link privato viene inviato automaticamente a quel numero; i link di condivisione restano revocabili."] }] },
    contact: { eyebrow: "Contatti", title: "Parla con una persona", intro: "Per supporto, privacy o sicurezza usa la conversazione WhatsApp ufficiale di Roastin senza includere la chat.", sections: [{ title: "Supporto", paragraphs: ["Invia ID del report e breve descrizione nella conversazione WhatsApp ufficiale di Roastin. Non allegare l’esportazione."] }, { title: "Privacy", paragraphs: ["Inizia con “Richiesta privacy”. Potremmo verificare l’identità WhatsApp. Tempi ufficiali e contatto del titolare saranno confermati prima del lancio."] }, { title: "Sicurezza", paragraphs: ["Inizia con “Segnalazione sicurezza”. Il canale WhatsApp Business deve essere attivato e monitorato prima del lancio."] }] },
    delete: { eyebrow: "Elimina dati", title: "Elimina report o account", intro: "Puoi eliminare il report dalla pagina privata e l’intero account dalle impostazioni.", sections: [{ title: "Elimina un report", paragraphs: ["Aprilo nel browser o account proprietario e scegli Elimina. Contenuto e anteprima vengono svuotati e i link smettono di funzionare. I pagamenti possono restare per legge."] }, { title: "Rimuovi dati di consegna", paragraphs: ["Dal report pagato rimuovi i dati di consegna: copia cifrata e impronta vengono cancellate e i link revocati."] }, { title: "Elimina un account", paragraphs: ["Apri le impostazioni dopo l’accesso con il numero WhatsApp verificato e scegli l’eliminazione permanente."] }] },
  },
} satisfies Dictionary;

export default dictionary;
