import en from "@/i18n/dictionaries/en";
import type { Dictionary } from "@/i18n/types";

const dictionary = {
  ...en,
  languageName: "Nederlands",
  common: { skipToContent: "Naar de inhoud", language: "Taal", close: "Sluiten", back: "Terug", continue: "Doorgaan", createReport: "Roast mijn chat", myReports: "Mijn rapporten", privacy: "Privacy", terms: "Voorwaarden", help: "Hulp", contact: "Contact", deleteData: "Mijn gegevens verwijderen", adultOnly: "Alleen 18+" },
  seo: { title: "Roastin Has Notes — Jullie groepschat, ongefilterd", description: "Upload een WhatsApp-gesprek en ontvang een privé, grappig en akelig raak rapport over jullie groepsdynamiek." },
  nav: { how: "Hoe het werkt", data: "Jouw gegevens", faq: "FAQ" },
  landing: { ...en.landing,
    eyebrow: "Het groepschatrapport", titleBefore: "Jouw chat heeft", titleAccent: "geheimen.", titleAfter: "Roastin maakt aantekeningen.", subtitle: "Upload een WhatsApp-gesprek. Ontvang het ongefilterde, verdacht rake rapport dat niemand in de groep durft te schrijven.", privacyNote: "De originele chat wordt na het maken niet bewaard", trust: ["Geverifieerd via WhatsApp", "Standaard privé", "Klaar in minuten"], ticker: ["Niemand vroeg erom.", "Roastin antwoordde.", "De bewijzen zijn binnen."],
    howEyebrow: "Belachelijk eenvoudig", howTitle: "Van groepschat naar hoofdpodium", howText: "Geen vragenlijsten of ongemakkelijke tests. Roastin gebruikt wat jullie al hebben gezegd.", steps: [{ title: "Lever het bewijs", text: "Exporteer je WhatsApp-chat en upload het .txt- of .zip-bestand." }, { title: "Roastin maakt notities", text: "Hij ziet terugkerende patronen en schrijft een rapport dat op het gesprek is gebaseerd." }, { title: "Lees, huiver, deel", text: "Krijg portretten, awards, inside jokes en een oordeel voor jullie groep." }],
    reportEyebrow: "Een rapport dat alleen jullie chat kon maken", reportTitle: "Algemene persoonlijkheidstests halen dit nooit.", reportText: "Elke observatie komt uit zichtbare patronen: wie plannen maakt, wie verdwijnt en wie precies één reactie-emoji kent.", features: ["Portretten van deelnemers", "Groepsawards", "Privéwoordenboek", "Verborgen dynamiek", "Groene, gele en rode vlaggen", "Voorspelde reacties"],
    privacyEyebrow: "Jouw chat blijft van jou", privacyTitle: "De roddels zijn heet. Onze opslag van de ruwe chat niet.", privacyText: "Het gesprek wordt tijdens de generatie versleuteld in tijdelijke opslag, nooit in onze applicatiedatabase bewaard en na verwerking verwijderd.", privacyCards: [{ title: "Eén doel", text: "Het gesprek wordt gebruikt om je rapport te genereren." }, { title: "Origineel niet bewaard", text: "De originele upload wordt na de aanvraag weggegooid." }, { title: "Rapport blijft privé", text: "Het afgeleide rapport wordt bewaard zodat je het kunt terugvinden en verwijderen." }],
    faqEyebrow: "Voor je de roddels overhandigt", faqTitle: "Terechte vragen.", faqs: [{ question: "Bewaren jullie mijn gesprek?", answer: "We slaan de originele export niet op in onze applicatiedatabase. Hij wordt verwerkt om het rapport te maken en daarna weggegooid. Het afgeleide rapport blijft privé tot jij het verwijdert." }, { question: "Komt de rest dit te weten?", answer: "Alleen als jij het vertelt. Rapporten zijn standaard privé en de aparte deellink kan worden ingetrokken." }, { question: "Is het gemeen?", answer: "Roastin richt zich op terugkerend gedrag, nooit op identiteit, uiterlijk of gevoelige kenmerken." }, { question: "Welke chats werken het best?", answer: "Actieve groepen zijn ideaal, maar stellen, beste vrienden, families en teams werken ook." }], finalTitle: "Jullie groepschat schreef het materiaal al.", finalText: "Roastin durft het alleen hardop te zeggen.", finalCta: "Lever het bewijs",
  },
  onboarding: { ...en.onboarding,
    step: "Stap", of: "van", back: "Terug", continue: "Doorgaan", close: "Sluiten", errors: { format: "Kies een WhatsApp-.txt-export of het .zip-archief.", size: "Deze bèta accepteert gesprekken tot 2 MB.", archive: "Dit archief bevat geen leesbare WhatsApp-tekstexport.", short: "We vonden niet genoeg berichten. Kies een onbewerkte WhatsApp-export.", generation: "Het rapport kon niet worden gemaakt. Probeer opnieuw." },
    types: { eyebrow: "Schets de situatie", title: "Met wat voor chat hebben we te maken?", text: "Elke groep heeft eigen natuurwetten. Dit helpt Roastin de sfeer te lezen.", options: { friends: { label: "Vriendengroep", detail: "De prachtige chaos" }, partner: { label: "Partner of crush", detail: "Lezen op eigen risico" }, "best-friend": { label: "Beste vriend", detail: "Een instituut voor twee" }, family: { label: "Familie", detail: "Generatieverhalen inbegrepen" }, work: { label: "Werk of team", detail: "Professioneel onprofessioneel" }, other: { label: "Iets anders", detail: "Roastin zoekt het uit" } } },
    context: { eyebrow: "Optionele context", title: "Moet Roastin iets weten?", text: "Eén zin is genoeg. Sla over als de berichten voor zich spreken.", placeholder: "We kennen elkaar sinds de universiteit en elke reis wordt zes weken onderhandelen…" },
    upload: { eyebrow: "Het bewijs", title: "Upload je WhatsApp-export.", text: "Kies het .txt- of .zip-bestand van een export zonder media. De eerste analyse gebeurt in je browser.", choose: "Kies je .txt- of .zip-bestand", limits: "Maximaal 2 MB · Geen media", messages: "berichten", participants: "deelnemers", replace: "Ander bestand kiezen", privacy: "Originele chat na generatie weggegooid", sample: "Probeer de voorbeeldchat" },
    review: { eyebrow: "De cast", title: "Controleer of we de groep goed begrijpen.", text: "Gebruik voornamen of bijnamen. Deze verschijnen in het rapport.", chatName: "Chatnaam", participantName: "Weergavenaam", invalidNames: "Iedere persoon heeft een unieke voornaam of bijnaam nodig." },
    launch: { ready: "Roastin is klaar voor", messages: "berichten", protagonists: "hoofdpersonen", warning: "Ze hebben geen idee wat ze gaan ontdekken.", cards: ["Patronen", "Portretten", "Oordeel"], consent: "Ik bevestig dat ik 18 jaar of ouder ben, dat dit gesprek geen minderjarigen betreft en dat ik instem met tijdelijke verwerking om het rapport te maken.", loading: "Tussen de regels lezen. Dit kan een minuut duren…", cta: "Laat Roastin koken" },
  },
  pages: {
    privacy: { eyebrow: "Privacy", title: "Wat we verwerken, bewaren en verwijderen", intro: "Deze duidelijke uitleg beschrijft hoe het product nu werkt. We beweren niet dat we niets opslaan.", sections: [
      { title: "Het originele gesprek", paragraphs: ["Je browser leest de export lokaal voor de eerste samenvatting. Bij een rapportaanvraag wordt het gesprek via HTTPS verzonden, worden duidelijke e-mails en telefoonnummers verwijderd en wordt het in het geheugen van onze server en de ingestelde AI-provider verwerkt.", "De export en transcriptie worden niet in onze applicatiedatabase geschreven en na de aanvraag weggegooid. We instrueren de AI-provider om geen gegevens te verzamelen, maar zijn eigen voorwaarden blijven gelden."] },
      { title: "Wat we bewaren", paragraphs: ["We bewaren het afgeleide rapport en voorbeeld, chatnaam, taal, geaggregeerde aantallen, datums, model-ID en registratie dat de ruwe verwerking klaar is."], bullets: ["Tijdelijk sessietoken als serverhash", "Geverifieerd en versleuteld WhatsApp-nummer, blinde index, toestemming en tijdelijke codes", "Stripe-betalingsreferenties", "Intrekbare deel- en bezorglinks", "WhatsApp-template, provider-ID en bezorgstatus"] },
      { title: "Doelen en termijnen", paragraphs: ["Gegevens dienen om de dienst te leveren en beveiligen, aankopen af te handelen, misbruik te voorkomen en plichten na te komen. Rapporten blijven tot verwijdering; sessies duren 30 dagen en bezorglinks 7 dagen."], bullets: ["Er is nog geen definitieve termijn voor versleutelde WhatsApp-nummers; je kunt ze direct verwijderen.", "Logs horen geen chatberichten te bevatten; leveranciers kunnen technische metadata bewaren."] },
      { title: "Jouw keuzes", paragraphs: ["Je kunt rapporten verwijderen, links intrekken en WhatsApp-gegevens wissen. Gebruik Contact voor inzage, correctie, export of accountverwijdering. Wettelijk vereiste betalingsgegevens kunnen blijven."] },
      { title: "Leveranciers en lanceringsstatus", paragraphs: ["Hosting, database, OpenRouter en modelprovider, Stripe en Meta voor WhatsApp-authenticatie en transactionele bezorging kunnen gegevens verwerken. Verwerkingsverantwoordelijke, adres, rechtsgronden, doorgiften en definitieve bewaartermijnen moeten voor lancering juridisch worden vastgelegd, ook voor niet-gebruikers."] },
    ] },
    terms: { eyebrow: "Voorwaarden", title: "Regels voor Roastin", intro: "Deze bètavoorwaarden leggen de grenzen uit. Definitieve bedrijfs- en rechtsgegevens ontbreken nog.", sections: [{ title: "Wie mag het gebruiken", paragraphs: ["Je moet minimaal 18 zijn. Upload geen chats met minderjarigen en zorg voor een geldige rechtsgrond en vereiste toestemming."] }, { title: "Aanvaardbaar gebruik", paragraphs: ["Gebruik Roastin niet voor intimidatie, bedreiging, discriminatie, het onthullen van contacten, belangrijke beslissingen of illegale inhoud. Omzeil geen toegangscontroles."] }, { title: "Het rapport", paragraphs: ["Het is geautomatiseerd entertainment uit zichtbare patronen en kan fout zijn. Het is geen psychologisch, medisch, juridisch, werk- of relatieadvies. Controleer voor delen."] }, { title: "Aankopen", paragraphs: ["Een rapport is een eenmalige digitale aankoop via Stripe. De getoonde prijs en valuta gelden. Terugbetaling, bedenktijd en belasting moeten per markt worden afgerond."] }, { title: "Beschikbaarheid", paragraphs: ["De bèta kan veranderen of uitvallen. Dwingende rechten blijven gelden. Toepasselijk recht en geschillen wachten op juridische beoordeling."] }] },
    help: { eyebrow: "Hulp", title: "Een schone export, een beter rapport", intro: "Snelle antwoorden over import, privacy, toegang en delen.", sections: [{ title: "Exporteren uit WhatsApp", paragraphs: ["Open de chat, kies Chat exporteren, Zonder media en upload .txt of .zip. Limiet: 2 MB."] }, { title: "Importproblemen", paragraphs: ["Gebruik een originele tekstexport met minstens twee deelnemers en acht berichten. Geen screenshots, pdf’s of media-archieven."] }, { title: "Privacy en veiligheid", paragraphs: ["Het origineel staat niet in onze database. Rapporten zijn privé. Chats met mogelijke minderjarigen worden geweigerd en duidelijke contactgegevens voor AI verwijderd."] }, { title: "Toegang en delen", paragraphs: ["Log in met je geverifieerde WhatsApp-nummer. Na betaling wordt de privélink automatisch naar dat nummer gestuurd; deellinks blijven intrekbaar."] }] },
    contact: { eyebrow: "Contact", title: "Praat met een mens", intro: "Gebruik voor hulp, privacy of veiligheid de officiële Roastin-conversatie op WhatsApp zonder chatinhoud mee te sturen.", sections: [{ title: "Support", paragraphs: ["Stuur rapport-ID en korte uitleg in de officiële Roastin-conversatie op WhatsApp. Voeg de export niet toe."] }, { title: "Privacy", paragraphs: ["Begin met “Privacyverzoek”. We kunnen je WhatsApp-identiteit verifiëren. Officiële termijn en verantwoordelijke worden voor lancering bevestigd."] }, { title: "Beveiliging", paragraphs: ["Begin met “Beveiligingsmelding”. Het WhatsApp Business-kanaal moet voor lancering actief en bewaakt zijn."] }] },
    delete: { eyebrow: "Gegevens verwijderen", title: "Verwijder rapport of account", intro: "Verwijder een rapport op de privépagina en het volledige account in de accountinstellingen.", sections: [{ title: "Rapport verwijderen", paragraphs: ["Open het in de browser of het account van de eigenaar en kies Verwijderen. Inhoud en voorbeeld worden gewist en links stoppen. Wettelijk vereiste betaalgegevens kunnen blijven."] }, { title: "Bezorggegevens verwijderen", paragraphs: ["Verwijder bezorggegevens vanuit het betaalde rapport. De versleutelde kopie en blinde index worden gewist en links ingetrokken."] }, { title: "Account verwijderen", paragraphs: ["Open na aanmelding met je geverifieerde WhatsApp-nummer de accountinstellingen en kies permanente verwijdering."] }] },
  },
} satisfies Dictionary;

export default dictionary;
