import en from "@/i18n/dictionaries/en";
import type { Dictionary } from "@/i18n/types";

const dictionary = {
  ...en,
  languageName: "Português",
  common: { skipToContent: "Ir para o conteúdo", language: "Idioma", close: "Fechar", back: "Voltar", continue: "Continuar", createReport: "Fazer roast ao chat", myReports: "Os meus relatórios", privacy: "Privacidade", terms: "Termos", help: "Ajuda", contact: "Contacto", deleteData: "Eliminar os meus dados", adultOnly: "Apenas maiores de 18" },
  seo: { title: "Roastin Has Notes — O teu chat, sem filtro", description: "Carrega uma conversa do WhatsApp e recebe um relatório privado, divertido e estranhamente certeiro sobre o teu grupo." },
  nav: { how: "Como funciona", data: "Os teus dados", faq: "FAQ" },
  landing: { ...en.landing,
    eyebrow: "O relatório do grupo", titleBefore: "O teu chat tem", titleAccent: "segredos.", titleAfter: "Roastin tomou notas.", subtitle: "Carrega uma conversa do WhatsApp. Recebe o relatório sem filtro e estranhamente certeiro que ninguém no grupo teria coragem de escrever.", privacyNote: "A conversa original não é guardada depois da geração", trust: ["Verificado por WhatsApp", "Privado por defeito", "Pronto em minutos"], ticker: ["Ninguém perguntou.", "Roastin respondeu.", "As provas chegaram."],
    howEyebrow: "Ridiculamente fácil", howTitle: "Do grupo ao evento principal", howText: "Sem questionários nem testes estranhos. Roastin usa aquilo que o grupo já disse.", steps: [{ title: "Entrega as provas", text: "Exporta o chat do WhatsApp e carrega o ficheiro .txt ou .zip." }, { title: "Roastin toma notas", text: "Encontra padrões repetidos e escreve um relatório baseado na conversa." }, { title: "Lê, espanta-te, partilha", text: "Recebe retratos, prémios, piadas internas e um veredicto feito para o grupo." }],
    reportEyebrow: "Um relatório que só o teu chat podia criar", reportTitle: "Os testes de personalidade genéricos não chegam perto.", reportText: "Cada observação vem de padrões visíveis: quem faz planos, quem desaparece e quem só usa um emoji.", features: ["Retratos dos participantes", "Prémios do grupo", "Dicionário privado", "Dinâmicas escondidas", "Sinais verdes, amarelos e vermelhos", "Reações previstas"],
    privacyEyebrow: "O teu chat continua teu", privacyTitle: "O mexerico está quente. O armazenamento da conversa original não.", privacyText: "A conversa é cifrada num armazenamento temporário durante a geração, nunca é guardada na base de dados da aplicação e é eliminada no fim do tratamento.", privacyCards: [{ title: "Uma só finalidade", text: "A conversa é usada para gerar o relatório." }, { title: "Original não guardado", text: "O ficheiro original é descartado no fim do pedido." }, { title: "Relatório privado", text: "O relatório derivado fica guardado para o consultares e eliminares." }],
    faqEyebrow: "Antes de entregares o mexerico", faqTitle: "Perguntas justas.", faqs: [{ question: "Guardam a minha conversa?", answer: "Não guardamos a exportação original na nossa base de dados. É processada para criar o relatório e descartada. O relatório derivado fica privado até o eliminares." }, { question: "Os outros vão saber?", answer: "Só se disseres. Os relatórios são privados e o link de partilha pode ser revogado." }, { question: "É cruel?", answer: "Roastin goza com comportamentos repetidos, nunca com identidade, aparência ou características sensíveis." }, { question: "Que chats funcionam melhor?", answer: "Grupos ativos são ideais, mas casais, melhores amigos, famílias e equipas também funcionam." }], finalTitle: "O teu grupo já escreveu o material.", finalText: "Roastin só tem coragem para o dizer em voz alta.", finalCta: "Entrega as provas",
  },
  onboarding: { ...en.onboarding,
    step: "Passo", of: "de", back: "Voltar", continue: "Continuar", close: "Fechar", errors: { format: "Escolhe uma exportação .txt do WhatsApp ou o arquivo .zip.", size: "Esta beta aceita conversas até 2 MB.", archive: "O arquivo não contém uma exportação de texto legível.", short: "Não encontrámos mensagens suficientes. Escolhe uma exportação original.", generation: "Não foi possível criar o relatório. Tenta novamente." },
    types: { eyebrow: "Prepara o cenário", title: "Que tipo de chat temos aqui?", text: "Cada grupo tem as suas leis da física. Isto ajuda Roastin a perceber o ambiente.", options: { friends: { label: "Grupo de amigos", detail: "O belo caos" }, partner: { label: "Parceiro ou crush", detail: "Lê por tua conta e risco" }, "best-friend": { label: "Melhor amigo", detail: "Uma instituição a dois" }, family: { label: "Família", detail: "História geracional incluída" }, work: { label: "Trabalho ou equipa", detail: "Profissionalmente pouco profissional" }, other: { label: "Outra coisa", detail: "Roastin vai perceber" } } },
    context: { eyebrow: "Contexto opcional", title: "Algo que Roastin deva saber?", text: "Uma frase chega. Salta se as mensagens falarem por si.", placeholder: "Conhecemo-nos desde a universidade e cada viagem vira seis semanas de negociação…" },
    upload: { eyebrow: "As provas", title: "Carrega a exportação do WhatsApp.", text: "Escolhe o .txt ou .zip de uma exportação sem multimédia. A primeira análise acontece no navegador.", choose: "Escolher .txt ou .zip", limits: "Máximo 2 MB · Sem multimédia", messages: "mensagens", participants: "participantes", replace: "Escolher outro ficheiro", privacy: "Conversa original descartada após a geração", sample: "Experimentar a conversa de exemplo" },
    review: { eyebrow: "Elenco", title: "Confirma que percebemos o grupo.", text: "Usa nomes próprios ou alcunhas. Serão mostrados no relatório.", chatName: "Nome do chat", participantName: "Nome apresentado", invalidNames: "Cada pessoa precisa de um nome próprio ou alcunha únicos." },
    verification: { eyebrow: "Um último passo", title: "Guarda o teu relatório.", text: "Verifica agora o número de WhatsApp para criar o relatório e receber a ligação privada.", phoneLabel: "Número de WhatsApp", consent: "Aceito receber o código de verificação e as ligações transacionais do relatório no WhatsApp. Sem marketing.", sendCode: "Enviar código pelo WhatsApp", codeTitle: "Consulta o WhatsApp.", codeText: "Enviámos um código de seis dígitos para {phone}.", codeLabel: "Código de seis dígitos", verifyAndLaunch: "Verificar e criar o relatório", differentNumber: "Usar outro número", sessionExpired: "A tua sessão expirou. Verifica o número de WhatsApp para continuar." },
    launch: { ready: "Roastin está pronto para", messages: "mensagens", protagonists: "protagonistas", warning: "Não fazem ideia do que vão descobrir.", cards: ["Padrões", "Retratos", "Veredicto"], consent: "Confirmo que tenho pelo menos 18 anos, que a conversa não envolve menores e consinto no processamento temporário para criar o relatório.", loading: "A ler nas entrelinhas. Pode demorar um minuto…", cta: "Deixar Roastin cozinhar" },
  },
  pages: {
    privacy: { eyebrow: "Privacidade", title: "O que processamos, guardamos e eliminamos", intro: "Este aviso descreve de forma simples o produto atual. Não afirma que não guardamos nada.", sections: [
      { title: "A conversa original", paragraphs: ["O navegador lê a exportação localmente para o resumo inicial. Ao pedir o relatório, a conversa segue por HTTPS, emails e telefones óbvios são removidos e o conteúdo é processado em memória pelo servidor e fornecedor de IA.", "A exportação e transcrição não são escritas na base de dados e são descartadas no fim do pedido. Pedimos ao fornecedor de IA que não recolha os dados, mas aplicam-se os seus termos."] },
      { title: "O que guardamos", paragraphs: ["Guardamos relatório derivado e pré-visualização, nome, idioma, totais agregados, datas, modelo e registo do fim do processamento."], bullets: ["Token de sessão temporário com hash", "Número WhatsApp verificado e cifrado, índice cego, consentimento e códigos temporários", "Referências Stripe", "Links de partilha e entrega revogáveis", "Modelo WhatsApp, ID do fornecedor e estado da entrega"] },
      { title: "Finalidades e prazos", paragraphs: ["Os dados servem para fornecer e proteger o serviço, concluir compras, prevenir abusos e cumprir obrigações. Relatórios ficam até serem eliminados; sessões duram 30 dias e links de entrega 7 dias."], bullets: ["O prazo final dos números WhatsApp cifrados ainda não está definido; podem ser removidos de imediato.", "Os logs não devem conter mensagens, mas fornecedores podem guardar metadados técnicos."] },
      { title: "As tuas escolhas", paragraphs: ["Podes eliminar relatórios, revogar links e retirar dados WhatsApp. Para acesso, correção, exportação ou eliminação da conta usa Contacto. Alguns registos de pagamento podem ficar por lei."] },
      { title: "Fornecedores e estado de lançamento", paragraphs: ["Podem intervir alojamento, base de dados, OpenRouter e modelo, Stripe e Meta para autenticação e entrega transacional por WhatsApp. Responsável, morada, bases legais, transferências e prazos definitivos, incluindo dados de não utilizadores, precisam de revisão jurídica antes do lançamento."] },
    ] },
    terms: { eyebrow: "Termos", title: "Regras para usar Roastin", intro: "Estes termos beta explicam os limites. Dados finais da empresa e jurisdição ainda são necessários.", sections: [{ title: "Quem pode usar", paragraphs: ["Tens de ter pelo menos 18 anos. Não carregues conversas com menores e garante base legal e permissões necessárias."] }, { title: "Uso aceitável", paragraphs: ["Não uses Roastin para assediar, ameaçar, discriminar, expor contactos, tomar decisões importantes ou analisar conteúdo ilegal. Não contornes controlos."] }, { title: "O relatório", paragraphs: ["É entretenimento automatizado baseado em padrões visíveis e pode errar. Não é aconselhamento psicológico, médico, legal, profissional ou relacional. Revê antes de partilhar."] }, { title: "Compras", paragraphs: ["O relatório é uma compra digital única via Stripe. Aplicam-se preço e moeda apresentados. Reembolsos, livre resolução e impostos devem ser definidos por mercado."] }, { title: "Disponibilidade", paragraphs: ["A beta pode mudar ou falhar. Direitos obrigatórios mantêm-se. Lei aplicável e litígios aguardam revisão jurídica."] }] },
    help: { eyebrow: "Ajuda", title: "Uma exportação limpa, um relatório melhor", intro: "Respostas rápidas sobre importação, privacidade, acesso e partilha.", sections: [{ title: "Exportar do WhatsApp", paragraphs: ["Abre o chat, escolhe Exportar conversa, Sem multimédia e carrega o .txt ou .zip. Limite: 2 MB."] }, { title: "Problemas de importação", paragraphs: ["Usa texto original com pelo menos duas pessoas e oito mensagens. Não envies capturas, PDF ou arquivos multimédia."] }, { title: "Privacidade e segurança", paragraphs: ["O original não é guardado na nossa base. Relatórios são privados. Recusamos chats com possíveis menores e removemos contactos óbvios antes da IA."] }, { title: "Acesso e partilha", paragraphs: ["Inicia sessão com o número WhatsApp verificado. Após o pagamento, a ligação privada é enviada automaticamente para esse número; as ligações de partilha continuam revogáveis."] }] },
    contact: { eyebrow: "Contacto", title: "Fala com uma pessoa", intro: "Para apoio, privacidade ou segurança usa a conversa WhatsApp oficial de Roastin sem incluir a conversa original.", sections: [{ title: "Apoio", paragraphs: ["Envia o ID do relatório e uma descrição breve na conversa WhatsApp oficial de Roastin. Não anexes o chat."] }, { title: "Privacidade", paragraphs: ["Começa com “Pedido de privacidade”. Podemos verificar a identidade WhatsApp. Prazo oficial e contacto responsável serão confirmados antes do lançamento."] }, { title: "Segurança", paragraphs: ["Começa com “Relatório de segurança”. O canal WhatsApp Business precisa de ser criado e monitorizado antes do lançamento."] }] },
    delete: { eyebrow: "Eliminar dados", title: "Elimina relatório ou conta", intro: "Podes eliminar o relatório na página privada e toda a conta nas definições.", sections: [{ title: "Eliminar relatório", paragraphs: ["Abre-o no navegador ou conta proprietária e escolhe Eliminar. Conteúdo e pré-visualização são limpos e links deixam de funcionar. Pagamentos podem ficar por lei."] }, { title: "Remover dados de entrega", paragraphs: ["No relatório pago remove dados de entrega. A cópia cifrada e o índice são apagados e os links revogados."] }, { title: "Eliminar conta", paragraphs: ["Abre as definições depois de iniciar sessão com o número WhatsApp verificado e escolhe a eliminação permanente."] }] },
  },
} satisfies Dictionary;

export default dictionary;
